/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
)

// OpsworksApplicationLister helps list OpsworksApplications.
type OpsworksApplicationLister interface {
	// List lists all OpsworksApplications in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.OpsworksApplication, err error)
	// OpsworksApplications returns an object that can list and get OpsworksApplications.
	OpsworksApplications(namespace string) OpsworksApplicationNamespaceLister
	OpsworksApplicationListerExpansion
}

// opsworksApplicationLister implements the OpsworksApplicationLister interface.
type opsworksApplicationLister struct {
	indexer cache.Indexer
}

// NewOpsworksApplicationLister returns a new OpsworksApplicationLister.
func NewOpsworksApplicationLister(indexer cache.Indexer) OpsworksApplicationLister {
	return &opsworksApplicationLister{indexer: indexer}
}

// List lists all OpsworksApplications in the indexer.
func (s *opsworksApplicationLister) List(selector labels.Selector) (ret []*v1alpha1.OpsworksApplication, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OpsworksApplication))
	})
	return ret, err
}

// OpsworksApplications returns an object that can list and get OpsworksApplications.
func (s *opsworksApplicationLister) OpsworksApplications(namespace string) OpsworksApplicationNamespaceLister {
	return opsworksApplicationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// OpsworksApplicationNamespaceLister helps list and get OpsworksApplications.
type OpsworksApplicationNamespaceLister interface {
	// List lists all OpsworksApplications in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.OpsworksApplication, err error)
	// Get retrieves the OpsworksApplication from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.OpsworksApplication, error)
	OpsworksApplicationNamespaceListerExpansion
}

// opsworksApplicationNamespaceLister implements the OpsworksApplicationNamespaceLister
// interface.
type opsworksApplicationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all OpsworksApplications in the indexer for a given namespace.
func (s opsworksApplicationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.OpsworksApplication, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OpsworksApplication))
	})
	return ret, err
}

// Get retrieves the OpsworksApplication from the indexer for a given namespace and name.
func (s opsworksApplicationNamespaceLister) Get(name string) (*v1alpha1.OpsworksApplication, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("opsworksapplication"), name)
	}
	return obj.(*v1alpha1.OpsworksApplication), nil
}
