/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// WafregionalWebACLAssociationLister helps list WafregionalWebACLAssociations.
type WafregionalWebACLAssociationLister interface {
	// List lists all WafregionalWebACLAssociations in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.WafregionalWebACLAssociation, err error)
	// WafregionalWebACLAssociations returns an object that can list and get WafregionalWebACLAssociations.
	WafregionalWebACLAssociations(namespace string) WafregionalWebACLAssociationNamespaceLister
	WafregionalWebACLAssociationListerExpansion
}

// wafregionalWebACLAssociationLister implements the WafregionalWebACLAssociationLister interface.
type wafregionalWebACLAssociationLister struct {
	indexer cache.Indexer
}

// NewWafregionalWebACLAssociationLister returns a new WafregionalWebACLAssociationLister.
func NewWafregionalWebACLAssociationLister(indexer cache.Indexer) WafregionalWebACLAssociationLister {
	return &wafregionalWebACLAssociationLister{indexer: indexer}
}

// List lists all WafregionalWebACLAssociations in the indexer.
func (s *wafregionalWebACLAssociationLister) List(selector labels.Selector) (ret []*v1alpha1.WafregionalWebACLAssociation, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WafregionalWebACLAssociation))
	})
	return ret, err
}

// WafregionalWebACLAssociations returns an object that can list and get WafregionalWebACLAssociations.
func (s *wafregionalWebACLAssociationLister) WafregionalWebACLAssociations(namespace string) WafregionalWebACLAssociationNamespaceLister {
	return wafregionalWebACLAssociationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// WafregionalWebACLAssociationNamespaceLister helps list and get WafregionalWebACLAssociations.
type WafregionalWebACLAssociationNamespaceLister interface {
	// List lists all WafregionalWebACLAssociations in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.WafregionalWebACLAssociation, err error)
	// Get retrieves the WafregionalWebACLAssociation from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.WafregionalWebACLAssociation, error)
	WafregionalWebACLAssociationNamespaceListerExpansion
}

// wafregionalWebACLAssociationNamespaceLister implements the WafregionalWebACLAssociationNamespaceLister
// interface.
type wafregionalWebACLAssociationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all WafregionalWebACLAssociations in the indexer for a given namespace.
func (s wafregionalWebACLAssociationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.WafregionalWebACLAssociation, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WafregionalWebACLAssociation))
	})
	return ret, err
}

// Get retrieves the WafregionalWebACLAssociation from the indexer for a given namespace and name.
func (s wafregionalWebACLAssociationNamespaceLister) Get(name string) (*v1alpha1.WafregionalWebACLAssociation, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("wafregionalwebaclassociation"), name)
	}
	return obj.(*v1alpha1.WafregionalWebACLAssociation), nil
}
