/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// AwsAppsyncApiKeysGetter has a method to return a AwsAppsyncApiKeyInterface.
// A group's client should implement this interface.
type AwsAppsyncApiKeysGetter interface {
	AwsAppsyncApiKeys() AwsAppsyncApiKeyInterface
}

// AwsAppsyncApiKeyInterface has methods to work with AwsAppsyncApiKey resources.
type AwsAppsyncApiKeyInterface interface {
	Create(*v1alpha1.AwsAppsyncApiKey) (*v1alpha1.AwsAppsyncApiKey, error)
	Update(*v1alpha1.AwsAppsyncApiKey) (*v1alpha1.AwsAppsyncApiKey, error)
	UpdateStatus(*v1alpha1.AwsAppsyncApiKey) (*v1alpha1.AwsAppsyncApiKey, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AwsAppsyncApiKey, error)
	List(opts v1.ListOptions) (*v1alpha1.AwsAppsyncApiKeyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsAppsyncApiKey, err error)
	AwsAppsyncApiKeyExpansion
}

// awsAppsyncApiKeys implements AwsAppsyncApiKeyInterface
type awsAppsyncApiKeys struct {
	client rest.Interface
}

// newAwsAppsyncApiKeys returns a AwsAppsyncApiKeys
func newAwsAppsyncApiKeys(c *AwsV1alpha1Client) *awsAppsyncApiKeys {
	return &awsAppsyncApiKeys{
		client: c.RESTClient(),
	}
}

// Get takes name of the awsAppsyncApiKey, and returns the corresponding awsAppsyncApiKey object, and an error if there is any.
func (c *awsAppsyncApiKeys) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsAppsyncApiKey, err error) {
	result = &v1alpha1.AwsAppsyncApiKey{}
	err = c.client.Get().
		Resource("awsappsyncapikeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsAppsyncApiKeys that match those selectors.
func (c *awsAppsyncApiKeys) List(opts v1.ListOptions) (result *v1alpha1.AwsAppsyncApiKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AwsAppsyncApiKeyList{}
	err = c.client.Get().
		Resource("awsappsyncapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsAppsyncApiKeys.
func (c *awsAppsyncApiKeys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("awsappsyncapikeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a awsAppsyncApiKey and creates it.  Returns the server's representation of the awsAppsyncApiKey, and an error, if there is any.
func (c *awsAppsyncApiKeys) Create(awsAppsyncApiKey *v1alpha1.AwsAppsyncApiKey) (result *v1alpha1.AwsAppsyncApiKey, err error) {
	result = &v1alpha1.AwsAppsyncApiKey{}
	err = c.client.Post().
		Resource("awsappsyncapikeys").
		Body(awsAppsyncApiKey).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsAppsyncApiKey and updates it. Returns the server's representation of the awsAppsyncApiKey, and an error, if there is any.
func (c *awsAppsyncApiKeys) Update(awsAppsyncApiKey *v1alpha1.AwsAppsyncApiKey) (result *v1alpha1.AwsAppsyncApiKey, err error) {
	result = &v1alpha1.AwsAppsyncApiKey{}
	err = c.client.Put().
		Resource("awsappsyncapikeys").
		Name(awsAppsyncApiKey.Name).
		Body(awsAppsyncApiKey).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *awsAppsyncApiKeys) UpdateStatus(awsAppsyncApiKey *v1alpha1.AwsAppsyncApiKey) (result *v1alpha1.AwsAppsyncApiKey, err error) {
	result = &v1alpha1.AwsAppsyncApiKey{}
	err = c.client.Put().
		Resource("awsappsyncapikeys").
		Name(awsAppsyncApiKey.Name).
		SubResource("status").
		Body(awsAppsyncApiKey).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsAppsyncApiKey and deletes it. Returns an error if one occurs.
func (c *awsAppsyncApiKeys) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("awsappsyncapikeys").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsAppsyncApiKeys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("awsappsyncapikeys").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsAppsyncApiKey.
func (c *awsAppsyncApiKeys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsAppsyncApiKey, err error) {
	result = &v1alpha1.AwsAppsyncApiKey{}
	err = c.client.Patch(pt).
		Resource("awsappsyncapikeys").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
