/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// AwsIamUserGroupMembershipsGetter has a method to return a AwsIamUserGroupMembershipInterface.
// A group's client should implement this interface.
type AwsIamUserGroupMembershipsGetter interface {
	AwsIamUserGroupMemberships() AwsIamUserGroupMembershipInterface
}

// AwsIamUserGroupMembershipInterface has methods to work with AwsIamUserGroupMembership resources.
type AwsIamUserGroupMembershipInterface interface {
	Create(*v1alpha1.AwsIamUserGroupMembership) (*v1alpha1.AwsIamUserGroupMembership, error)
	Update(*v1alpha1.AwsIamUserGroupMembership) (*v1alpha1.AwsIamUserGroupMembership, error)
	UpdateStatus(*v1alpha1.AwsIamUserGroupMembership) (*v1alpha1.AwsIamUserGroupMembership, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AwsIamUserGroupMembership, error)
	List(opts v1.ListOptions) (*v1alpha1.AwsIamUserGroupMembershipList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsIamUserGroupMembership, err error)
	AwsIamUserGroupMembershipExpansion
}

// awsIamUserGroupMemberships implements AwsIamUserGroupMembershipInterface
type awsIamUserGroupMemberships struct {
	client rest.Interface
}

// newAwsIamUserGroupMemberships returns a AwsIamUserGroupMemberships
func newAwsIamUserGroupMemberships(c *AwsV1alpha1Client) *awsIamUserGroupMemberships {
	return &awsIamUserGroupMemberships{
		client: c.RESTClient(),
	}
}

// Get takes name of the awsIamUserGroupMembership, and returns the corresponding awsIamUserGroupMembership object, and an error if there is any.
func (c *awsIamUserGroupMemberships) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsIamUserGroupMembership, err error) {
	result = &v1alpha1.AwsIamUserGroupMembership{}
	err = c.client.Get().
		Resource("awsiamusergroupmemberships").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsIamUserGroupMemberships that match those selectors.
func (c *awsIamUserGroupMemberships) List(opts v1.ListOptions) (result *v1alpha1.AwsIamUserGroupMembershipList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AwsIamUserGroupMembershipList{}
	err = c.client.Get().
		Resource("awsiamusergroupmemberships").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsIamUserGroupMemberships.
func (c *awsIamUserGroupMemberships) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("awsiamusergroupmemberships").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a awsIamUserGroupMembership and creates it.  Returns the server's representation of the awsIamUserGroupMembership, and an error, if there is any.
func (c *awsIamUserGroupMemberships) Create(awsIamUserGroupMembership *v1alpha1.AwsIamUserGroupMembership) (result *v1alpha1.AwsIamUserGroupMembership, err error) {
	result = &v1alpha1.AwsIamUserGroupMembership{}
	err = c.client.Post().
		Resource("awsiamusergroupmemberships").
		Body(awsIamUserGroupMembership).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsIamUserGroupMembership and updates it. Returns the server's representation of the awsIamUserGroupMembership, and an error, if there is any.
func (c *awsIamUserGroupMemberships) Update(awsIamUserGroupMembership *v1alpha1.AwsIamUserGroupMembership) (result *v1alpha1.AwsIamUserGroupMembership, err error) {
	result = &v1alpha1.AwsIamUserGroupMembership{}
	err = c.client.Put().
		Resource("awsiamusergroupmemberships").
		Name(awsIamUserGroupMembership.Name).
		Body(awsIamUserGroupMembership).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *awsIamUserGroupMemberships) UpdateStatus(awsIamUserGroupMembership *v1alpha1.AwsIamUserGroupMembership) (result *v1alpha1.AwsIamUserGroupMembership, err error) {
	result = &v1alpha1.AwsIamUserGroupMembership{}
	err = c.client.Put().
		Resource("awsiamusergroupmemberships").
		Name(awsIamUserGroupMembership.Name).
		SubResource("status").
		Body(awsIamUserGroupMembership).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsIamUserGroupMembership and deletes it. Returns an error if one occurs.
func (c *awsIamUserGroupMemberships) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("awsiamusergroupmemberships").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsIamUserGroupMemberships) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("awsiamusergroupmemberships").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsIamUserGroupMembership.
func (c *awsIamUserGroupMemberships) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsIamUserGroupMembership, err error) {
	result = &v1alpha1.AwsIamUserGroupMembership{}
	err = c.client.Patch(pt).
		Resource("awsiamusergroupmemberships").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
