/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// AwsNeptuneClusterSnapshotsGetter has a method to return a AwsNeptuneClusterSnapshotInterface.
// A group's client should implement this interface.
type AwsNeptuneClusterSnapshotsGetter interface {
	AwsNeptuneClusterSnapshots() AwsNeptuneClusterSnapshotInterface
}

// AwsNeptuneClusterSnapshotInterface has methods to work with AwsNeptuneClusterSnapshot resources.
type AwsNeptuneClusterSnapshotInterface interface {
	Create(*v1alpha1.AwsNeptuneClusterSnapshot) (*v1alpha1.AwsNeptuneClusterSnapshot, error)
	Update(*v1alpha1.AwsNeptuneClusterSnapshot) (*v1alpha1.AwsNeptuneClusterSnapshot, error)
	UpdateStatus(*v1alpha1.AwsNeptuneClusterSnapshot) (*v1alpha1.AwsNeptuneClusterSnapshot, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AwsNeptuneClusterSnapshot, error)
	List(opts v1.ListOptions) (*v1alpha1.AwsNeptuneClusterSnapshotList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsNeptuneClusterSnapshot, err error)
	AwsNeptuneClusterSnapshotExpansion
}

// awsNeptuneClusterSnapshots implements AwsNeptuneClusterSnapshotInterface
type awsNeptuneClusterSnapshots struct {
	client rest.Interface
}

// newAwsNeptuneClusterSnapshots returns a AwsNeptuneClusterSnapshots
func newAwsNeptuneClusterSnapshots(c *AwsV1alpha1Client) *awsNeptuneClusterSnapshots {
	return &awsNeptuneClusterSnapshots{
		client: c.RESTClient(),
	}
}

// Get takes name of the awsNeptuneClusterSnapshot, and returns the corresponding awsNeptuneClusterSnapshot object, and an error if there is any.
func (c *awsNeptuneClusterSnapshots) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsNeptuneClusterSnapshot, err error) {
	result = &v1alpha1.AwsNeptuneClusterSnapshot{}
	err = c.client.Get().
		Resource("awsneptuneclustersnapshots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsNeptuneClusterSnapshots that match those selectors.
func (c *awsNeptuneClusterSnapshots) List(opts v1.ListOptions) (result *v1alpha1.AwsNeptuneClusterSnapshotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AwsNeptuneClusterSnapshotList{}
	err = c.client.Get().
		Resource("awsneptuneclustersnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsNeptuneClusterSnapshots.
func (c *awsNeptuneClusterSnapshots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("awsneptuneclustersnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a awsNeptuneClusterSnapshot and creates it.  Returns the server's representation of the awsNeptuneClusterSnapshot, and an error, if there is any.
func (c *awsNeptuneClusterSnapshots) Create(awsNeptuneClusterSnapshot *v1alpha1.AwsNeptuneClusterSnapshot) (result *v1alpha1.AwsNeptuneClusterSnapshot, err error) {
	result = &v1alpha1.AwsNeptuneClusterSnapshot{}
	err = c.client.Post().
		Resource("awsneptuneclustersnapshots").
		Body(awsNeptuneClusterSnapshot).
		Do().
		Into(result)
	return
}

// Update takes the representation of a awsNeptuneClusterSnapshot and updates it. Returns the server's representation of the awsNeptuneClusterSnapshot, and an error, if there is any.
func (c *awsNeptuneClusterSnapshots) Update(awsNeptuneClusterSnapshot *v1alpha1.AwsNeptuneClusterSnapshot) (result *v1alpha1.AwsNeptuneClusterSnapshot, err error) {
	result = &v1alpha1.AwsNeptuneClusterSnapshot{}
	err = c.client.Put().
		Resource("awsneptuneclustersnapshots").
		Name(awsNeptuneClusterSnapshot.Name).
		Body(awsNeptuneClusterSnapshot).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *awsNeptuneClusterSnapshots) UpdateStatus(awsNeptuneClusterSnapshot *v1alpha1.AwsNeptuneClusterSnapshot) (result *v1alpha1.AwsNeptuneClusterSnapshot, err error) {
	result = &v1alpha1.AwsNeptuneClusterSnapshot{}
	err = c.client.Put().
		Resource("awsneptuneclustersnapshots").
		Name(awsNeptuneClusterSnapshot.Name).
		SubResource("status").
		Body(awsNeptuneClusterSnapshot).
		Do().
		Into(result)
	return
}

// Delete takes name of the awsNeptuneClusterSnapshot and deletes it. Returns an error if one occurs.
func (c *awsNeptuneClusterSnapshots) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("awsneptuneclustersnapshots").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsNeptuneClusterSnapshots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("awsneptuneclustersnapshots").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched awsNeptuneClusterSnapshot.
func (c *awsNeptuneClusterSnapshots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsNeptuneClusterSnapshot, err error) {
	result = &v1alpha1.AwsNeptuneClusterSnapshot{}
	err = c.client.Patch(pt).
		Resource("awsneptuneclustersnapshots").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
