/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackupPlansGetter has a method to return a BackupPlanInterface.
// A group's client should implement this interface.
type BackupPlansGetter interface {
	BackupPlans(namespace string) BackupPlanInterface
}

// BackupPlanInterface has methods to work with BackupPlan resources.
type BackupPlanInterface interface {
	Create(*v1alpha1.BackupPlan) (*v1alpha1.BackupPlan, error)
	Update(*v1alpha1.BackupPlan) (*v1alpha1.BackupPlan, error)
	UpdateStatus(*v1alpha1.BackupPlan) (*v1alpha1.BackupPlan, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.BackupPlan, error)
	List(opts v1.ListOptions) (*v1alpha1.BackupPlanList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BackupPlan, err error)
	BackupPlanExpansion
}

// backupPlans implements BackupPlanInterface
type backupPlans struct {
	client rest.Interface
	ns     string
}

// newBackupPlans returns a BackupPlans
func newBackupPlans(c *AwsV1alpha1Client, namespace string) *backupPlans {
	return &backupPlans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backupPlan, and returns the corresponding backupPlan object, and an error if there is any.
func (c *backupPlans) Get(name string, options v1.GetOptions) (result *v1alpha1.BackupPlan, err error) {
	result = &v1alpha1.BackupPlan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupplans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackupPlans that match those selectors.
func (c *backupPlans) List(opts v1.ListOptions) (result *v1alpha1.BackupPlanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BackupPlanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backupPlans.
func (c *backupPlans) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backupplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a backupPlan and creates it.  Returns the server's representation of the backupPlan, and an error, if there is any.
func (c *backupPlans) Create(backupPlan *v1alpha1.BackupPlan) (result *v1alpha1.BackupPlan, err error) {
	result = &v1alpha1.BackupPlan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backupplans").
		Body(backupPlan).
		Do().
		Into(result)
	return
}

// Update takes the representation of a backupPlan and updates it. Returns the server's representation of the backupPlan, and an error, if there is any.
func (c *backupPlans) Update(backupPlan *v1alpha1.BackupPlan) (result *v1alpha1.BackupPlan, err error) {
	result = &v1alpha1.BackupPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupplans").
		Name(backupPlan.Name).
		Body(backupPlan).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *backupPlans) UpdateStatus(backupPlan *v1alpha1.BackupPlan) (result *v1alpha1.BackupPlan, err error) {
	result = &v1alpha1.BackupPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupplans").
		Name(backupPlan.Name).
		SubResource("status").
		Body(backupPlan).
		Do().
		Into(result)
	return
}

// Delete takes name of the backupPlan and deletes it. Returns an error if one occurs.
func (c *backupPlans) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupplans").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backupPlans) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupplans").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched backupPlan.
func (c *backupPlans) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BackupPlan, err error) {
	result = &v1alpha1.BackupPlan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backupplans").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
