/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ElasticBeanstalkConfigurationTemplatesGetter has a method to return a ElasticBeanstalkConfigurationTemplateInterface.
// A group's client should implement this interface.
type ElasticBeanstalkConfigurationTemplatesGetter interface {
	ElasticBeanstalkConfigurationTemplates(namespace string) ElasticBeanstalkConfigurationTemplateInterface
}

// ElasticBeanstalkConfigurationTemplateInterface has methods to work with ElasticBeanstalkConfigurationTemplate resources.
type ElasticBeanstalkConfigurationTemplateInterface interface {
	Create(*v1alpha1.ElasticBeanstalkConfigurationTemplate) (*v1alpha1.ElasticBeanstalkConfigurationTemplate, error)
	Update(*v1alpha1.ElasticBeanstalkConfigurationTemplate) (*v1alpha1.ElasticBeanstalkConfigurationTemplate, error)
	UpdateStatus(*v1alpha1.ElasticBeanstalkConfigurationTemplate) (*v1alpha1.ElasticBeanstalkConfigurationTemplate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ElasticBeanstalkConfigurationTemplate, error)
	List(opts v1.ListOptions) (*v1alpha1.ElasticBeanstalkConfigurationTemplateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ElasticBeanstalkConfigurationTemplate, err error)
	ElasticBeanstalkConfigurationTemplateExpansion
}

// elasticBeanstalkConfigurationTemplates implements ElasticBeanstalkConfigurationTemplateInterface
type elasticBeanstalkConfigurationTemplates struct {
	client rest.Interface
	ns     string
}

// newElasticBeanstalkConfigurationTemplates returns a ElasticBeanstalkConfigurationTemplates
func newElasticBeanstalkConfigurationTemplates(c *AwsV1alpha1Client, namespace string) *elasticBeanstalkConfigurationTemplates {
	return &elasticBeanstalkConfigurationTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the elasticBeanstalkConfigurationTemplate, and returns the corresponding elasticBeanstalkConfigurationTemplate object, and an error if there is any.
func (c *elasticBeanstalkConfigurationTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.ElasticBeanstalkConfigurationTemplate, err error) {
	result = &v1alpha1.ElasticBeanstalkConfigurationTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ElasticBeanstalkConfigurationTemplates that match those selectors.
func (c *elasticBeanstalkConfigurationTemplates) List(opts v1.ListOptions) (result *v1alpha1.ElasticBeanstalkConfigurationTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ElasticBeanstalkConfigurationTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested elasticBeanstalkConfigurationTemplates.
func (c *elasticBeanstalkConfigurationTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a elasticBeanstalkConfigurationTemplate and creates it.  Returns the server's representation of the elasticBeanstalkConfigurationTemplate, and an error, if there is any.
func (c *elasticBeanstalkConfigurationTemplates) Create(elasticBeanstalkConfigurationTemplate *v1alpha1.ElasticBeanstalkConfigurationTemplate) (result *v1alpha1.ElasticBeanstalkConfigurationTemplate, err error) {
	result = &v1alpha1.ElasticBeanstalkConfigurationTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		Body(elasticBeanstalkConfigurationTemplate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a elasticBeanstalkConfigurationTemplate and updates it. Returns the server's representation of the elasticBeanstalkConfigurationTemplate, and an error, if there is any.
func (c *elasticBeanstalkConfigurationTemplates) Update(elasticBeanstalkConfigurationTemplate *v1alpha1.ElasticBeanstalkConfigurationTemplate) (result *v1alpha1.ElasticBeanstalkConfigurationTemplate, err error) {
	result = &v1alpha1.ElasticBeanstalkConfigurationTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		Name(elasticBeanstalkConfigurationTemplate.Name).
		Body(elasticBeanstalkConfigurationTemplate).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *elasticBeanstalkConfigurationTemplates) UpdateStatus(elasticBeanstalkConfigurationTemplate *v1alpha1.ElasticBeanstalkConfigurationTemplate) (result *v1alpha1.ElasticBeanstalkConfigurationTemplate, err error) {
	result = &v1alpha1.ElasticBeanstalkConfigurationTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		Name(elasticBeanstalkConfigurationTemplate.Name).
		SubResource("status").
		Body(elasticBeanstalkConfigurationTemplate).
		Do().
		Into(result)
	return
}

// Delete takes name of the elasticBeanstalkConfigurationTemplate and deletes it. Returns an error if one occurs.
func (c *elasticBeanstalkConfigurationTemplates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *elasticBeanstalkConfigurationTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched elasticBeanstalkConfigurationTemplate.
func (c *elasticBeanstalkConfigurationTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ElasticBeanstalkConfigurationTemplate, err error) {
	result = &v1alpha1.ElasticBeanstalkConfigurationTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("elasticbeanstalkconfigurationtemplates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
