/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// Route53ResolverEndpointsGetter has a method to return a Route53ResolverEndpointInterface.
// A group's client should implement this interface.
type Route53ResolverEndpointsGetter interface {
	Route53ResolverEndpoints(namespace string) Route53ResolverEndpointInterface
}

// Route53ResolverEndpointInterface has methods to work with Route53ResolverEndpoint resources.
type Route53ResolverEndpointInterface interface {
	Create(*v1alpha1.Route53ResolverEndpoint) (*v1alpha1.Route53ResolverEndpoint, error)
	Update(*v1alpha1.Route53ResolverEndpoint) (*v1alpha1.Route53ResolverEndpoint, error)
	UpdateStatus(*v1alpha1.Route53ResolverEndpoint) (*v1alpha1.Route53ResolverEndpoint, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Route53ResolverEndpoint, error)
	List(opts v1.ListOptions) (*v1alpha1.Route53ResolverEndpointList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Route53ResolverEndpoint, err error)
	Route53ResolverEndpointExpansion
}

// route53ResolverEndpoints implements Route53ResolverEndpointInterface
type route53ResolverEndpoints struct {
	client rest.Interface
	ns     string
}

// newRoute53ResolverEndpoints returns a Route53ResolverEndpoints
func newRoute53ResolverEndpoints(c *AwsV1alpha1Client, namespace string) *route53ResolverEndpoints {
	return &route53ResolverEndpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the route53ResolverEndpoint, and returns the corresponding route53ResolverEndpoint object, and an error if there is any.
func (c *route53ResolverEndpoints) Get(name string, options v1.GetOptions) (result *v1alpha1.Route53ResolverEndpoint, err error) {
	result = &v1alpha1.Route53ResolverEndpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Route53ResolverEndpoints that match those selectors.
func (c *route53ResolverEndpoints) List(opts v1.ListOptions) (result *v1alpha1.Route53ResolverEndpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.Route53ResolverEndpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested route53ResolverEndpoints.
func (c *route53ResolverEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a route53ResolverEndpoint and creates it.  Returns the server's representation of the route53ResolverEndpoint, and an error, if there is any.
func (c *route53ResolverEndpoints) Create(route53ResolverEndpoint *v1alpha1.Route53ResolverEndpoint) (result *v1alpha1.Route53ResolverEndpoint, err error) {
	result = &v1alpha1.Route53ResolverEndpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		Body(route53ResolverEndpoint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a route53ResolverEndpoint and updates it. Returns the server's representation of the route53ResolverEndpoint, and an error, if there is any.
func (c *route53ResolverEndpoints) Update(route53ResolverEndpoint *v1alpha1.Route53ResolverEndpoint) (result *v1alpha1.Route53ResolverEndpoint, err error) {
	result = &v1alpha1.Route53ResolverEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		Name(route53ResolverEndpoint.Name).
		Body(route53ResolverEndpoint).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *route53ResolverEndpoints) UpdateStatus(route53ResolverEndpoint *v1alpha1.Route53ResolverEndpoint) (result *v1alpha1.Route53ResolverEndpoint, err error) {
	result = &v1alpha1.Route53ResolverEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		Name(route53ResolverEndpoint.Name).
		SubResource("status").
		Body(route53ResolverEndpoint).
		Do().
		Into(result)
	return
}

// Delete takes name of the route53ResolverEndpoint and deletes it. Returns an error if one occurs.
func (c *route53ResolverEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *route53ResolverEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched route53ResolverEndpoint.
func (c *route53ResolverEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Route53ResolverEndpoint, err error) {
	result = &v1alpha1.Route53ResolverEndpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("route53resolverendpoints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
