/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StoragegatewayCachesGetter has a method to return a StoragegatewayCacheInterface.
// A group's client should implement this interface.
type StoragegatewayCachesGetter interface {
	StoragegatewayCaches(namespace string) StoragegatewayCacheInterface
}

// StoragegatewayCacheInterface has methods to work with StoragegatewayCache resources.
type StoragegatewayCacheInterface interface {
	Create(*v1alpha1.StoragegatewayCache) (*v1alpha1.StoragegatewayCache, error)
	Update(*v1alpha1.StoragegatewayCache) (*v1alpha1.StoragegatewayCache, error)
	UpdateStatus(*v1alpha1.StoragegatewayCache) (*v1alpha1.StoragegatewayCache, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StoragegatewayCache, error)
	List(opts v1.ListOptions) (*v1alpha1.StoragegatewayCacheList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StoragegatewayCache, err error)
	StoragegatewayCacheExpansion
}

// storagegatewayCaches implements StoragegatewayCacheInterface
type storagegatewayCaches struct {
	client rest.Interface
	ns     string
}

// newStoragegatewayCaches returns a StoragegatewayCaches
func newStoragegatewayCaches(c *AwsV1alpha1Client, namespace string) *storagegatewayCaches {
	return &storagegatewayCaches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storagegatewayCache, and returns the corresponding storagegatewayCache object, and an error if there is any.
func (c *storagegatewayCaches) Get(name string, options v1.GetOptions) (result *v1alpha1.StoragegatewayCache, err error) {
	result = &v1alpha1.StoragegatewayCache{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StoragegatewayCaches that match those selectors.
func (c *storagegatewayCaches) List(opts v1.ListOptions) (result *v1alpha1.StoragegatewayCacheList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StoragegatewayCacheList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storagegatewayCaches.
func (c *storagegatewayCaches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a storagegatewayCache and creates it.  Returns the server's representation of the storagegatewayCache, and an error, if there is any.
func (c *storagegatewayCaches) Create(storagegatewayCache *v1alpha1.StoragegatewayCache) (result *v1alpha1.StoragegatewayCache, err error) {
	result = &v1alpha1.StoragegatewayCache{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		Body(storagegatewayCache).
		Do().
		Into(result)
	return
}

// Update takes the representation of a storagegatewayCache and updates it. Returns the server's representation of the storagegatewayCache, and an error, if there is any.
func (c *storagegatewayCaches) Update(storagegatewayCache *v1alpha1.StoragegatewayCache) (result *v1alpha1.StoragegatewayCache, err error) {
	result = &v1alpha1.StoragegatewayCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		Name(storagegatewayCache.Name).
		Body(storagegatewayCache).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *storagegatewayCaches) UpdateStatus(storagegatewayCache *v1alpha1.StoragegatewayCache) (result *v1alpha1.StoragegatewayCache, err error) {
	result = &v1alpha1.StoragegatewayCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		Name(storagegatewayCache.Name).
		SubResource("status").
		Body(storagegatewayCache).
		Do().
		Into(result)
	return
}

// Delete takes name of the storagegatewayCache and deletes it. Returns an error if one occurs.
func (c *storagegatewayCaches) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storagegatewayCaches) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched storagegatewayCache.
func (c *storagegatewayCaches) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StoragegatewayCache, err error) {
	result = &v1alpha1.StoragegatewayCache{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storagegatewaycaches").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
