/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeAzurermNetworkInterfaceBackendAddressPoolAssociations implements AzurermNetworkInterfaceBackendAddressPoolAssociationInterface
type FakeAzurermNetworkInterfaceBackendAddressPoolAssociations struct {
	Fake *FakeAzurermV1alpha1
}

var azurermnetworkinterfacebackendaddresspoolassociationsResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "azurermnetworkinterfacebackendaddresspoolassociations"}

var azurermnetworkinterfacebackendaddresspoolassociationsKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "AzurermNetworkInterfaceBackendAddressPoolAssociation"}

// Get takes name of the azurermNetworkInterfaceBackendAddressPoolAssociation, and returns the corresponding azurermNetworkInterfaceBackendAddressPoolAssociation object, and an error if there is any.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) Get(name string, options v1.GetOptions) (result *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, name), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation), err
}

// List takes label and field selectors, and returns the list of AzurermNetworkInterfaceBackendAddressPoolAssociations that match those selectors.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) List(opts v1.ListOptions) (result *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, azurermnetworkinterfacebackendaddresspoolassociationsKind, opts), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociationList{ListMeta: obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociationList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azurermNetworkInterfaceBackendAddressPoolAssociations.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, opts))
}

// Create takes the representation of a azurermNetworkInterfaceBackendAddressPoolAssociation and creates it.  Returns the server's representation of the azurermNetworkInterfaceBackendAddressPoolAssociation, and an error, if there is any.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) Create(azurermNetworkInterfaceBackendAddressPoolAssociation *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation) (result *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, azurermNetworkInterfaceBackendAddressPoolAssociation), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation), err
}

// Update takes the representation of a azurermNetworkInterfaceBackendAddressPoolAssociation and updates it. Returns the server's representation of the azurermNetworkInterfaceBackendAddressPoolAssociation, and an error, if there is any.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) Update(azurermNetworkInterfaceBackendAddressPoolAssociation *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation) (result *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, azurermNetworkInterfaceBackendAddressPoolAssociation), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) UpdateStatus(azurermNetworkInterfaceBackendAddressPoolAssociation *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation) (*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, "status", azurermNetworkInterfaceBackendAddressPoolAssociation), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation), err
}

// Delete takes name of the azurermNetworkInterfaceBackendAddressPoolAssociation and deletes it. Returns an error if one occurs.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, name), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociationList{})
	return err
}

// Patch applies the patch and returns the patched azurermNetworkInterfaceBackendAddressPoolAssociation.
func (c *FakeAzurermNetworkInterfaceBackendAddressPoolAssociations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(azurermnetworkinterfacebackendaddresspoolassociationsResource, name, pt, data, subresources...), &v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzurermNetworkInterfaceBackendAddressPoolAssociation), err
}
