/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCosmosdbCassandraKeyspaces implements CosmosdbCassandraKeyspaceInterface
type FakeCosmosdbCassandraKeyspaces struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var cosmosdbcassandrakeyspacesResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "cosmosdbcassandrakeyspaces"}

var cosmosdbcassandrakeyspacesKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "CosmosdbCassandraKeyspace"}

// Get takes name of the cosmosdbCassandraKeyspace, and returns the corresponding cosmosdbCassandraKeyspace object, and an error if there is any.
func (c *FakeCosmosdbCassandraKeyspaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CosmosdbCassandraKeyspace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cosmosdbcassandrakeyspacesResource, c.ns, name), &v1alpha1.CosmosdbCassandraKeyspace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CosmosdbCassandraKeyspace), err
}

// List takes label and field selectors, and returns the list of CosmosdbCassandraKeyspaces that match those selectors.
func (c *FakeCosmosdbCassandraKeyspaces) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CosmosdbCassandraKeyspaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cosmosdbcassandrakeyspacesResource, cosmosdbcassandrakeyspacesKind, c.ns, opts), &v1alpha1.CosmosdbCassandraKeyspaceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CosmosdbCassandraKeyspaceList{ListMeta: obj.(*v1alpha1.CosmosdbCassandraKeyspaceList).ListMeta}
	for _, item := range obj.(*v1alpha1.CosmosdbCassandraKeyspaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cosmosdbCassandraKeyspaces.
func (c *FakeCosmosdbCassandraKeyspaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cosmosdbcassandrakeyspacesResource, c.ns, opts))

}

// Create takes the representation of a cosmosdbCassandraKeyspace and creates it.  Returns the server's representation of the cosmosdbCassandraKeyspace, and an error, if there is any.
func (c *FakeCosmosdbCassandraKeyspaces) Create(ctx context.Context, cosmosdbCassandraKeyspace *v1alpha1.CosmosdbCassandraKeyspace, opts v1.CreateOptions) (result *v1alpha1.CosmosdbCassandraKeyspace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cosmosdbcassandrakeyspacesResource, c.ns, cosmosdbCassandraKeyspace), &v1alpha1.CosmosdbCassandraKeyspace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CosmosdbCassandraKeyspace), err
}

// Update takes the representation of a cosmosdbCassandraKeyspace and updates it. Returns the server's representation of the cosmosdbCassandraKeyspace, and an error, if there is any.
func (c *FakeCosmosdbCassandraKeyspaces) Update(ctx context.Context, cosmosdbCassandraKeyspace *v1alpha1.CosmosdbCassandraKeyspace, opts v1.UpdateOptions) (result *v1alpha1.CosmosdbCassandraKeyspace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cosmosdbcassandrakeyspacesResource, c.ns, cosmosdbCassandraKeyspace), &v1alpha1.CosmosdbCassandraKeyspace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CosmosdbCassandraKeyspace), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCosmosdbCassandraKeyspaces) UpdateStatus(ctx context.Context, cosmosdbCassandraKeyspace *v1alpha1.CosmosdbCassandraKeyspace, opts v1.UpdateOptions) (*v1alpha1.CosmosdbCassandraKeyspace, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cosmosdbcassandrakeyspacesResource, "status", c.ns, cosmosdbCassandraKeyspace), &v1alpha1.CosmosdbCassandraKeyspace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CosmosdbCassandraKeyspace), err
}

// Delete takes name of the cosmosdbCassandraKeyspace and deletes it. Returns an error if one occurs.
func (c *FakeCosmosdbCassandraKeyspaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cosmosdbcassandrakeyspacesResource, c.ns, name), &v1alpha1.CosmosdbCassandraKeyspace{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCosmosdbCassandraKeyspaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cosmosdbcassandrakeyspacesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CosmosdbCassandraKeyspaceList{})
	return err
}

// Patch applies the patch and returns the patched cosmosdbCassandraKeyspace.
func (c *FakeCosmosdbCassandraKeyspaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CosmosdbCassandraKeyspace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cosmosdbcassandrakeyspacesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CosmosdbCassandraKeyspace{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CosmosdbCassandraKeyspace), err
}
