/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkSecurityRules implements NetworkSecurityRuleInterface
type FakeNetworkSecurityRules struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var networksecurityrulesResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "networksecurityrules"}

var networksecurityrulesKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "NetworkSecurityRule"}

// Get takes name of the networkSecurityRule, and returns the corresponding networkSecurityRule object, and an error if there is any.
func (c *FakeNetworkSecurityRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkSecurityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networksecurityrulesResource, c.ns, name), &v1alpha1.NetworkSecurityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSecurityRule), err
}

// List takes label and field selectors, and returns the list of NetworkSecurityRules that match those selectors.
func (c *FakeNetworkSecurityRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkSecurityRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networksecurityrulesResource, networksecurityrulesKind, c.ns, opts), &v1alpha1.NetworkSecurityRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkSecurityRuleList{ListMeta: obj.(*v1alpha1.NetworkSecurityRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkSecurityRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkSecurityRules.
func (c *FakeNetworkSecurityRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networksecurityrulesResource, c.ns, opts))

}

// Create takes the representation of a networkSecurityRule and creates it.  Returns the server's representation of the networkSecurityRule, and an error, if there is any.
func (c *FakeNetworkSecurityRules) Create(ctx context.Context, networkSecurityRule *v1alpha1.NetworkSecurityRule, opts v1.CreateOptions) (result *v1alpha1.NetworkSecurityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networksecurityrulesResource, c.ns, networkSecurityRule), &v1alpha1.NetworkSecurityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSecurityRule), err
}

// Update takes the representation of a networkSecurityRule and updates it. Returns the server's representation of the networkSecurityRule, and an error, if there is any.
func (c *FakeNetworkSecurityRules) Update(ctx context.Context, networkSecurityRule *v1alpha1.NetworkSecurityRule, opts v1.UpdateOptions) (result *v1alpha1.NetworkSecurityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networksecurityrulesResource, c.ns, networkSecurityRule), &v1alpha1.NetworkSecurityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSecurityRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkSecurityRules) UpdateStatus(ctx context.Context, networkSecurityRule *v1alpha1.NetworkSecurityRule, opts v1.UpdateOptions) (*v1alpha1.NetworkSecurityRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networksecurityrulesResource, "status", c.ns, networkSecurityRule), &v1alpha1.NetworkSecurityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSecurityRule), err
}

// Delete takes name of the networkSecurityRule and deletes it. Returns an error if one occurs.
func (c *FakeNetworkSecurityRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networksecurityrulesResource, c.ns, name), &v1alpha1.NetworkSecurityRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkSecurityRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networksecurityrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkSecurityRuleList{})
	return err
}

// Patch applies the patch and returns the patched networkSecurityRule.
func (c *FakeNetworkSecurityRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkSecurityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networksecurityrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetworkSecurityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkSecurityRule), err
}
