/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataFactoryLinkedServiceDataLakeStorageGen2s implements DataFactoryLinkedServiceDataLakeStorageGen2Interface
type FakeDataFactoryLinkedServiceDataLakeStorageGen2s struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var datafactorylinkedservicedatalakestoragegen2sResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "datafactorylinkedservicedatalakestoragegen2s"}

var datafactorylinkedservicedatalakestoragegen2sKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "DataFactoryLinkedServiceDataLakeStorageGen2"}

// Get takes name of the dataFactoryLinkedServiceDataLakeStorageGen2, and returns the corresponding dataFactoryLinkedServiceDataLakeStorageGen2 object, and an error if there is any.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, name), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2), err
}

// List takes label and field selectors, and returns the list of DataFactoryLinkedServiceDataLakeStorageGen2s that match those selectors.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datafactorylinkedservicedatalakestoragegen2sResource, datafactorylinkedservicedatalakestoragegen2sKind, c.ns, opts), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2List{ListMeta: obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2List).ListMeta}
	for _, item := range obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataFactoryLinkedServiceDataLakeStorageGen2s.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, opts))

}

// Create takes the representation of a dataFactoryLinkedServiceDataLakeStorageGen2 and creates it.  Returns the server's representation of the dataFactoryLinkedServiceDataLakeStorageGen2, and an error, if there is any.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) Create(ctx context.Context, dataFactoryLinkedServiceDataLakeStorageGen2 *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, opts v1.CreateOptions) (result *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, dataFactoryLinkedServiceDataLakeStorageGen2), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2), err
}

// Update takes the representation of a dataFactoryLinkedServiceDataLakeStorageGen2 and updates it. Returns the server's representation of the dataFactoryLinkedServiceDataLakeStorageGen2, and an error, if there is any.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) Update(ctx context.Context, dataFactoryLinkedServiceDataLakeStorageGen2 *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, opts v1.UpdateOptions) (result *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, dataFactoryLinkedServiceDataLakeStorageGen2), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) UpdateStatus(ctx context.Context, dataFactoryLinkedServiceDataLakeStorageGen2 *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, opts v1.UpdateOptions) (*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(datafactorylinkedservicedatalakestoragegen2sResource, "status", c.ns, dataFactoryLinkedServiceDataLakeStorageGen2), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2), err
}

// Delete takes name of the dataFactoryLinkedServiceDataLakeStorageGen2 and deletes it. Returns an error if one occurs.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, name), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2List{})
	return err
}

// Patch applies the patch and returns the patched dataFactoryLinkedServiceDataLakeStorageGen2.
func (c *FakeDataFactoryLinkedServiceDataLakeStorageGen2s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datafactorylinkedservicedatalakestoragegen2sResource, c.ns, name, pt, data, subresources...), &v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataFactoryLinkedServiceDataLakeStorageGen2), err
}
