/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/google/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// GoogleProjectIamBindingsGetter has a method to return a GoogleProjectIamBindingInterface.
// A group's client should implement this interface.
type GoogleProjectIamBindingsGetter interface {
	GoogleProjectIamBindings() GoogleProjectIamBindingInterface
}

// GoogleProjectIamBindingInterface has methods to work with GoogleProjectIamBinding resources.
type GoogleProjectIamBindingInterface interface {
	Create(*v1alpha1.GoogleProjectIamBinding) (*v1alpha1.GoogleProjectIamBinding, error)
	Update(*v1alpha1.GoogleProjectIamBinding) (*v1alpha1.GoogleProjectIamBinding, error)
	UpdateStatus(*v1alpha1.GoogleProjectIamBinding) (*v1alpha1.GoogleProjectIamBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GoogleProjectIamBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.GoogleProjectIamBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GoogleProjectIamBinding, err error)
	GoogleProjectIamBindingExpansion
}

// googleProjectIamBindings implements GoogleProjectIamBindingInterface
type googleProjectIamBindings struct {
	client rest.Interface
}

// newGoogleProjectIamBindings returns a GoogleProjectIamBindings
func newGoogleProjectIamBindings(c *GoogleV1alpha1Client) *googleProjectIamBindings {
	return &googleProjectIamBindings{
		client: c.RESTClient(),
	}
}

// Get takes name of the googleProjectIamBinding, and returns the corresponding googleProjectIamBinding object, and an error if there is any.
func (c *googleProjectIamBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.GoogleProjectIamBinding, err error) {
	result = &v1alpha1.GoogleProjectIamBinding{}
	err = c.client.Get().
		Resource("googleprojectiambindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GoogleProjectIamBindings that match those selectors.
func (c *googleProjectIamBindings) List(opts v1.ListOptions) (result *v1alpha1.GoogleProjectIamBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GoogleProjectIamBindingList{}
	err = c.client.Get().
		Resource("googleprojectiambindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested googleProjectIamBindings.
func (c *googleProjectIamBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("googleprojectiambindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a googleProjectIamBinding and creates it.  Returns the server's representation of the googleProjectIamBinding, and an error, if there is any.
func (c *googleProjectIamBindings) Create(googleProjectIamBinding *v1alpha1.GoogleProjectIamBinding) (result *v1alpha1.GoogleProjectIamBinding, err error) {
	result = &v1alpha1.GoogleProjectIamBinding{}
	err = c.client.Post().
		Resource("googleprojectiambindings").
		Body(googleProjectIamBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a googleProjectIamBinding and updates it. Returns the server's representation of the googleProjectIamBinding, and an error, if there is any.
func (c *googleProjectIamBindings) Update(googleProjectIamBinding *v1alpha1.GoogleProjectIamBinding) (result *v1alpha1.GoogleProjectIamBinding, err error) {
	result = &v1alpha1.GoogleProjectIamBinding{}
	err = c.client.Put().
		Resource("googleprojectiambindings").
		Name(googleProjectIamBinding.Name).
		Body(googleProjectIamBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *googleProjectIamBindings) UpdateStatus(googleProjectIamBinding *v1alpha1.GoogleProjectIamBinding) (result *v1alpha1.GoogleProjectIamBinding, err error) {
	result = &v1alpha1.GoogleProjectIamBinding{}
	err = c.client.Put().
		Resource("googleprojectiambindings").
		Name(googleProjectIamBinding.Name).
		SubResource("status").
		Body(googleProjectIamBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the googleProjectIamBinding and deletes it. Returns an error if one occurs.
func (c *googleProjectIamBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("googleprojectiambindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *googleProjectIamBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("googleprojectiambindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched googleProjectIamBinding.
func (c *googleProjectIamBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GoogleProjectIamBinding, err error) {
	result = &v1alpha1.GoogleProjectIamBinding{}
	err = c.client.Patch(pt).
		Resource("googleprojectiambindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
