apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: ecsservices.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: EcsService
    listKind: EcsServiceList
    plural: ecsservices
    singular: ecsservice
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            deploymentController:
              items:
                properties:
                  type:
                    type: string
                type: object
              maxItems: 1
              type: array
            deploymentMaximumPercent:
              format: int64
              type: integer
            deploymentMinimumHealthyPercent:
              format: int64
              type: integer
            desiredCount:
              format: int64
              type: integer
            enableEcsManagedTags:
              type: boolean
            healthCheckGracePeriodSeconds:
              format: int64
              type: integer
            iamRole:
              type: string
            id:
              type: string
            launchType:
              type: string
            loadBalancer:
              items:
                properties:
                  containerName:
                    type: string
                  containerPort:
                    format: int64
                    type: integer
                  elbName:
                    type: string
                  targetGroupArn:
                    type: string
                required:
                - containerName
                - containerPort
                type: object
              maxItems: 1
              type: array
            name:
              type: string
            networkConfiguration:
              items:
                properties:
                  assignPublicIP:
                    type: boolean
                  securityGroups:
                    items:
                      type: string
                    type: array
                  subnets:
                    items:
                      type: string
                    type: array
                required:
                - subnets
                type: object
              maxItems: 1
              type: array
            orderedPlacementStrategy:
              items:
                properties:
                  field:
                    type: string
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 5
              type: array
            placementConstraints:
              items:
                properties:
                  expression:
                    type: string
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 10
              type: array
            platformVersion:
              type: string
            propagateTags:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            schedulingStrategy:
              type: string
            serviceRegistries:
              items:
                properties:
                  containerName:
                    type: string
                  containerPort:
                    format: int64
                    type: integer
                  port:
                    format: int64
                    type: integer
                  registryArn:
                    type: string
                required:
                - registryArn
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            taskDefinition:
              type: string
          required:
          - name
          - providerRef
          - taskDefinition
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                cluster:
                  type: string
                deploymentController:
                  items:
                    properties:
                      type:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                deploymentMaximumPercent:
                  format: int64
                  type: integer
                deploymentMinimumHealthyPercent:
                  format: int64
                  type: integer
                desiredCount:
                  format: int64
                  type: integer
                enableEcsManagedTags:
                  type: boolean
                healthCheckGracePeriodSeconds:
                  format: int64
                  type: integer
                iamRole:
                  type: string
                id:
                  type: string
                launchType:
                  type: string
                loadBalancer:
                  items:
                    properties:
                      containerName:
                        type: string
                      containerPort:
                        format: int64
                        type: integer
                      elbName:
                        type: string
                      targetGroupArn:
                        type: string
                    required:
                    - containerName
                    - containerPort
                    type: object
                  maxItems: 1
                  type: array
                name:
                  type: string
                networkConfiguration:
                  items:
                    properties:
                      assignPublicIP:
                        type: boolean
                      securityGroups:
                        items:
                          type: string
                        type: array
                      subnets:
                        items:
                          type: string
                        type: array
                    required:
                    - subnets
                    type: object
                  maxItems: 1
                  type: array
                orderedPlacementStrategy:
                  items:
                    properties:
                      field:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 5
                  type: array
                placementConstraints:
                  items:
                    properties:
                      expression:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 10
                  type: array
                platformVersion:
                  type: string
                propagateTags:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                schedulingStrategy:
                  type: string
                serviceRegistries:
                  items:
                    properties:
                      containerName:
                        type: string
                      containerPort:
                        format: int64
                        type: integer
                      port:
                        format: int64
                        type: integer
                      registryArn:
                        type: string
                    required:
                    - registryArn
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                taskDefinition:
                  type: string
              required:
              - name
              - providerRef
              - taskDefinition
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
