apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: redshiftclusters.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: RedshiftCluster
    listKind: RedshiftClusterList
    plural: redshiftclusters
    singular: redshiftcluster
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            allowVersionUpgrade:
              type: boolean
            arn:
              type: string
            automatedSnapshotRetentionPeriod:
              format: int64
              type: integer
            availabilityZone:
              type: string
            clusterIdentifier:
              type: string
            clusterParameterGroupName:
              type: string
            clusterPublicKey:
              type: string
            clusterRevisionNumber:
              type: string
            clusterSecurityGroups:
              items:
                type: string
              type: array
            clusterSubnetGroupName:
              type: string
            clusterType:
              type: string
            clusterVersion:
              type: string
            databaseName:
              type: string
            dnsName:
              type: string
            elasticIP:
              type: string
            encrypted:
              type: boolean
            endpoint:
              type: string
            enhancedVpcRouting:
              type: boolean
            finalSnapshotIdentifier:
              type: string
            iamRoles:
              items:
                type: string
              type: array
            id:
              type: string
            kmsKeyID:
              type: string
            logging:
              items:
                properties:
                  bucketName:
                    type: string
                  enable:
                    type: boolean
                  s3KeyPrefix:
                    type: string
                required:
                - enable
                type: object
              maxItems: 1
              type: array
            masterUsername:
              type: string
            nodeType:
              type: string
            numberOfNodes:
              format: int64
              type: integer
            ownerAccount:
              type: string
            port:
              format: int64
              type: integer
            preferredMaintenanceWindow:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publiclyAccessible:
              type: boolean
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            skipFinalSnapshot:
              type: boolean
            snapshotClusterIdentifier:
              type: string
            snapshotCopy:
              items:
                properties:
                  destinationRegion:
                    type: string
                  grantName:
                    type: string
                  retentionPeriod:
                    format: int64
                    type: integer
                required:
                - destinationRegion
                type: object
              maxItems: 1
              type: array
            snapshotIdentifier:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            vpcSecurityGroupIDS:
              items:
                type: string
              type: array
          required:
          - clusterIdentifier
          - nodeType
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                allowVersionUpgrade:
                  type: boolean
                arn:
                  type: string
                automatedSnapshotRetentionPeriod:
                  format: int64
                  type: integer
                availabilityZone:
                  type: string
                clusterIdentifier:
                  type: string
                clusterParameterGroupName:
                  type: string
                clusterPublicKey:
                  type: string
                clusterRevisionNumber:
                  type: string
                clusterSecurityGroups:
                  items:
                    type: string
                  type: array
                clusterSubnetGroupName:
                  type: string
                clusterType:
                  type: string
                clusterVersion:
                  type: string
                databaseName:
                  type: string
                dnsName:
                  type: string
                elasticIP:
                  type: string
                encrypted:
                  type: boolean
                endpoint:
                  type: string
                enhancedVpcRouting:
                  type: boolean
                finalSnapshotIdentifier:
                  type: string
                iamRoles:
                  items:
                    type: string
                  type: array
                id:
                  type: string
                kmsKeyID:
                  type: string
                logging:
                  items:
                    properties:
                      bucketName:
                        type: string
                      enable:
                        type: boolean
                      s3KeyPrefix:
                        type: string
                    required:
                    - enable
                    type: object
                  maxItems: 1
                  type: array
                masterUsername:
                  type: string
                nodeType:
                  type: string
                numberOfNodes:
                  format: int64
                  type: integer
                ownerAccount:
                  type: string
                port:
                  format: int64
                  type: integer
                preferredMaintenanceWindow:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publiclyAccessible:
                  type: boolean
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                skipFinalSnapshot:
                  type: boolean
                snapshotClusterIdentifier:
                  type: string
                snapshotCopy:
                  items:
                    properties:
                      destinationRegion:
                        type: string
                      grantName:
                        type: string
                      retentionPeriod:
                        format: int64
                        type: integer
                    required:
                    - destinationRegion
                    type: object
                  maxItems: 1
                  type: array
                snapshotIdentifier:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                vpcSecurityGroupIDS:
                  items:
                    type: string
                  type: array
              required:
              - clusterIdentifier
              - nodeType
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
