apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: spotfleetrequests.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: SpotFleetRequest
    listKind: SpotFleetRequestList
    plural: spotfleetrequests
    singular: spotfleetrequest
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            allocationStrategy:
              type: string
            clientToken:
              type: string
            excessCapacityTerminationPolicy:
              type: string
            fleetType:
              type: string
            iamFleetRole:
              type: string
            id:
              type: string
            instanceInterruptionBehaviour:
              type: string
            instancePoolsToUseCount:
              format: int64
              type: integer
            launchSpecification:
              items:
                properties:
                  ami:
                    type: string
                  associatePublicIPAddress:
                    type: boolean
                  availabilityZone:
                    type: string
                  ebsBlockDevice:
                    items:
                      properties:
                        deleteOnTermination:
                          type: boolean
                        deviceName:
                          type: string
                        encrypted:
                          type: boolean
                        iops:
                          format: int64
                          type: integer
                        snapshotID:
                          type: string
                        volumeSize:
                          format: int64
                          type: integer
                        volumeType:
                          type: string
                      required:
                      - deviceName
                      type: object
                    type: array
                  ebsOptimized:
                    type: boolean
                  ephemeralBlockDevice:
                    items:
                      properties:
                        deviceName:
                          type: string
                        virtualName:
                          type: string
                      required:
                      - deviceName
                      - virtualName
                      type: object
                    type: array
                  iamInstanceProfile:
                    type: string
                  iamInstanceProfileArn:
                    type: string
                  instanceType:
                    type: string
                  keyName:
                    type: string
                  monitoring:
                    type: boolean
                  placementGroup:
                    type: string
                  placementTenancy:
                    type: string
                  rootBlockDevice:
                    items:
                      properties:
                        deleteOnTermination:
                          type: boolean
                        iops:
                          format: int64
                          type: integer
                        volumeSize:
                          format: int64
                          type: integer
                        volumeType:
                          type: string
                      type: object
                    type: array
                  spotPrice:
                    type: string
                  subnetID:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  userData:
                    type: string
                  vpcSecurityGroupIDS:
                    items:
                      type: string
                    type: array
                  weightedCapacity:
                    type: string
                required:
                - ami
                - instanceType
                type: object
              type: array
            loadBalancers:
              items:
                type: string
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            replaceUnhealthyInstances:
              type: boolean
            spotPrice:
              type: string
            spotRequestState:
              type: string
            targetCapacity:
              format: int64
              type: integer
            targetGroupArns:
              items:
                type: string
              type: array
            terminateInstancesWithExpiration:
              type: boolean
            validFrom:
              type: string
            validUntil:
              type: string
            waitForFulfillment:
              type: boolean
          required:
          - iamFleetRole
          - launchSpecification
          - providerRef
          - targetCapacity
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                allocationStrategy:
                  type: string
                clientToken:
                  type: string
                excessCapacityTerminationPolicy:
                  type: string
                fleetType:
                  type: string
                iamFleetRole:
                  type: string
                id:
                  type: string
                instanceInterruptionBehaviour:
                  type: string
                instancePoolsToUseCount:
                  format: int64
                  type: integer
                launchSpecification:
                  items:
                    properties:
                      ami:
                        type: string
                      associatePublicIPAddress:
                        type: boolean
                      availabilityZone:
                        type: string
                      ebsBlockDevice:
                        items:
                          properties:
                            deleteOnTermination:
                              type: boolean
                            deviceName:
                              type: string
                            encrypted:
                              type: boolean
                            iops:
                              format: int64
                              type: integer
                            snapshotID:
                              type: string
                            volumeSize:
                              format: int64
                              type: integer
                            volumeType:
                              type: string
                          required:
                          - deviceName
                          type: object
                        type: array
                      ebsOptimized:
                        type: boolean
                      ephemeralBlockDevice:
                        items:
                          properties:
                            deviceName:
                              type: string
                            virtualName:
                              type: string
                          required:
                          - deviceName
                          - virtualName
                          type: object
                        type: array
                      iamInstanceProfile:
                        type: string
                      iamInstanceProfileArn:
                        type: string
                      instanceType:
                        type: string
                      keyName:
                        type: string
                      monitoring:
                        type: boolean
                      placementGroup:
                        type: string
                      placementTenancy:
                        type: string
                      rootBlockDevice:
                        items:
                          properties:
                            deleteOnTermination:
                              type: boolean
                            iops:
                              format: int64
                              type: integer
                            volumeSize:
                              format: int64
                              type: integer
                            volumeType:
                              type: string
                          type: object
                        type: array
                      spotPrice:
                        type: string
                      subnetID:
                        type: string
                      tags:
                        additionalProperties:
                          type: string
                        type: object
                      userData:
                        type: string
                      vpcSecurityGroupIDS:
                        items:
                          type: string
                        type: array
                      weightedCapacity:
                        type: string
                    required:
                    - ami
                    - instanceType
                    type: object
                  type: array
                loadBalancers:
                  items:
                    type: string
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                replaceUnhealthyInstances:
                  type: boolean
                spotPrice:
                  type: string
                spotRequestState:
                  type: string
                targetCapacity:
                  format: int64
                  type: integer
                targetGroupArns:
                  items:
                    type: string
                  type: array
                terminateInstancesWithExpiration:
                  type: boolean
                validFrom:
                  type: string
                validUntil:
                  type: string
                waitForFulfillment:
                  type: boolean
              required:
              - iamFleetRole
              - launchSpecification
              - providerRef
              - targetCapacity
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
