apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: monitoractivitylogalerts.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: MonitorActivityLogAlert
    listKind: MonitorActivityLogAlertList
    plural: monitoractivitylogalerts
    singular: monitoractivitylogalert
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            action:
              items:
                properties:
                  actionGroupID:
                    type: string
                  webhookProperties:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - actionGroupID
                type: object
              type: array
            criteria:
              items:
                properties:
                  caller:
                    type: string
                  category:
                    type: string
                  level:
                    type: string
                  operationName:
                    type: string
                  resourceGroup:
                    type: string
                  resourceID:
                    type: string
                  resourceProvider:
                    type: string
                  resourceType:
                    type: string
                  status:
                    type: string
                  subStatus:
                    type: string
                required:
                - category
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            enabled:
              type: boolean
            id:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            scopes:
              items:
                type: string
              minItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - criteria
          - name
          - providerRef
          - resourceGroupName
          - scopes
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                action:
                  items:
                    properties:
                      actionGroupID:
                        type: string
                      webhookProperties:
                        additionalProperties:
                          type: string
                        type: object
                    required:
                    - actionGroupID
                    type: object
                  type: array
                criteria:
                  items:
                    properties:
                      caller:
                        type: string
                      category:
                        type: string
                      level:
                        type: string
                      operationName:
                        type: string
                      resourceGroup:
                        type: string
                      resourceID:
                        type: string
                      resourceProvider:
                        type: string
                      resourceType:
                        type: string
                      status:
                        type: string
                      subStatus:
                        type: string
                    required:
                    - category
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                enabled:
                  type: boolean
                id:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                scopes:
                  items:
                    type: string
                  minItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - criteria
              - name
              - providerRef
              - resourceGroupName
              - scopes
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
