apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: datafactorylinkedservicedatalakestoragegen2s.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: DataFactoryLinkedServiceDataLakeStorageGen2
    listKind: DataFactoryLinkedServiceDataLakeStorageGen2List
    plural: datafactorylinkedservicedatalakestoragegen2s
    singular: datafactorylinkedservicedatalakestoragegen2
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalProperties:
              additionalProperties:
                type: string
              type: object
            annotations:
              items:
                type: string
              type: array
            dataFactoryName:
              type: string
            description:
              type: string
            id:
              type: string
            integrationRuntimeName:
              type: string
            name:
              type: string
            parameters:
              additionalProperties:
                type: string
              type: object
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            servicePrincipalID:
              type: string
            servicePrincipalKey:
              type: string
            tenant:
              type: string
            url:
              type: string
          required:
          - dataFactoryName
          - name
          - providerRef
          - resourceGroupName
          - servicePrincipalID
          - servicePrincipalKey
          - tenant
          - url
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                additionalProperties:
                  additionalProperties:
                    type: string
                  type: object
                annotations:
                  items:
                    type: string
                  type: array
                dataFactoryName:
                  type: string
                description:
                  type: string
                id:
                  type: string
                integrationRuntimeName:
                  type: string
                name:
                  type: string
                parameters:
                  additionalProperties:
                    type: string
                  type: object
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                servicePrincipalID:
                  type: string
                servicePrincipalKey:
                  type: string
                tenant:
                  type: string
                url:
                  type: string
              required:
              - dataFactoryName
              - name
              - providerRef
              - resourceGroupName
              - servicePrincipalID
              - servicePrincipalKey
              - tenant
              - url
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
