apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: packetcaptures.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: PacketCapture
    listKind: PacketCaptureList
    plural: packetcaptures
    singular: packetcapture
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            filter:
              items:
                properties:
                  localIPAddress:
                    type: string
                  localPort:
                    type: string
                  protocol:
                    type: string
                  remoteIPAddress:
                    type: string
                  remotePort:
                    type: string
                required:
                - protocol
                type: object
              type: array
            id:
              type: string
            maximumBytesPerPacket:
              format: int64
              type: integer
            maximumBytesPerSession:
              format: int64
              type: integer
            maximumCaptureDuration:
              format: int64
              type: integer
            name:
              type: string
            networkWatcherName:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            storageLocation:
              items:
                properties:
                  filePath:
                    type: string
                  storageAccountID:
                    type: string
                  storagePath:
                    type: string
                type: object
              maxItems: 1
              type: array
            targetResourceID:
              type: string
          required:
          - name
          - networkWatcherName
          - providerRef
          - resourceGroupName
          - storageLocation
          - targetResourceID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                filter:
                  items:
                    properties:
                      localIPAddress:
                        type: string
                      localPort:
                        type: string
                      protocol:
                        type: string
                      remoteIPAddress:
                        type: string
                      remotePort:
                        type: string
                    required:
                    - protocol
                    type: object
                  type: array
                id:
                  type: string
                maximumBytesPerPacket:
                  format: int64
                  type: integer
                maximumBytesPerSession:
                  format: int64
                  type: integer
                maximumCaptureDuration:
                  format: int64
                  type: integer
                name:
                  type: string
                networkWatcherName:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                storageLocation:
                  items:
                    properties:
                      filePath:
                        type: string
                      storageAccountID:
                        type: string
                      storagePath:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                targetResourceID:
                  type: string
              required:
              - name
              - networkWatcherName
              - providerRef
              - resourceGroupName
              - storageLocation
              - targetResourceID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
