/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "kubeform.dev/kubeform/apis/digitalocean/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SpacesBucketObjectsGetter has a method to return a SpacesBucketObjectInterface.
// A group's client should implement this interface.
type SpacesBucketObjectsGetter interface {
	SpacesBucketObjects(namespace string) SpacesBucketObjectInterface
}

// SpacesBucketObjectInterface has methods to work with SpacesBucketObject resources.
type SpacesBucketObjectInterface interface {
	Create(*v1alpha1.SpacesBucketObject) (*v1alpha1.SpacesBucketObject, error)
	Update(*v1alpha1.SpacesBucketObject) (*v1alpha1.SpacesBucketObject, error)
	UpdateStatus(*v1alpha1.SpacesBucketObject) (*v1alpha1.SpacesBucketObject, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SpacesBucketObject, error)
	List(opts v1.ListOptions) (*v1alpha1.SpacesBucketObjectList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SpacesBucketObject, err error)
	SpacesBucketObjectExpansion
}

// spacesBucketObjects implements SpacesBucketObjectInterface
type spacesBucketObjects struct {
	client rest.Interface
	ns     string
}

// newSpacesBucketObjects returns a SpacesBucketObjects
func newSpacesBucketObjects(c *DigitaloceanV1alpha1Client, namespace string) *spacesBucketObjects {
	return &spacesBucketObjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the spacesBucketObject, and returns the corresponding spacesBucketObject object, and an error if there is any.
func (c *spacesBucketObjects) Get(name string, options v1.GetOptions) (result *v1alpha1.SpacesBucketObject, err error) {
	result = &v1alpha1.SpacesBucketObject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SpacesBucketObjects that match those selectors.
func (c *spacesBucketObjects) List(opts v1.ListOptions) (result *v1alpha1.SpacesBucketObjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SpacesBucketObjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested spacesBucketObjects.
func (c *spacesBucketObjects) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a spacesBucketObject and creates it.  Returns the server's representation of the spacesBucketObject, and an error, if there is any.
func (c *spacesBucketObjects) Create(spacesBucketObject *v1alpha1.SpacesBucketObject) (result *v1alpha1.SpacesBucketObject, err error) {
	result = &v1alpha1.SpacesBucketObject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		Body(spacesBucketObject).
		Do().
		Into(result)
	return
}

// Update takes the representation of a spacesBucketObject and updates it. Returns the server's representation of the spacesBucketObject, and an error, if there is any.
func (c *spacesBucketObjects) Update(spacesBucketObject *v1alpha1.SpacesBucketObject) (result *v1alpha1.SpacesBucketObject, err error) {
	result = &v1alpha1.SpacesBucketObject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		Name(spacesBucketObject.Name).
		Body(spacesBucketObject).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *spacesBucketObjects) UpdateStatus(spacesBucketObject *v1alpha1.SpacesBucketObject) (result *v1alpha1.SpacesBucketObject, err error) {
	result = &v1alpha1.SpacesBucketObject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		Name(spacesBucketObject.Name).
		SubResource("status").
		Body(spacesBucketObject).
		Do().
		Into(result)
	return
}

// Delete takes name of the spacesBucketObject and deletes it. Returns an error if one occurs.
func (c *spacesBucketObjects) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *spacesBucketObjects) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched spacesBucketObject.
func (c *spacesBucketObjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SpacesBucketObject, err error) {
	result = &v1alpha1.SpacesBucketObject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("spacesbucketobjects").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
