apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: dbinstances.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DbInstance
    listKind: DbInstanceList
    plural: dbinstances
    singular: dbinstance
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            address:
              type: string
            allocatedStorage:
              format: int64
              type: integer
            allowMajorVersionUpgrade:
              type: boolean
            applyImmediately:
              type: boolean
            arn:
              type: string
            autoMinorVersionUpgrade:
              type: boolean
            availabilityZone:
              type: string
            backupRetentionPeriod:
              format: int64
              type: integer
            backupWindow:
              type: string
            caCertIdentifier:
              type: string
            characterSetName:
              type: string
            copyTagsToSnapshot:
              type: boolean
            dbSubnetGroupName:
              type: string
            deletionProtection:
              type: boolean
            domain:
              type: string
            domainIamRoleName:
              type: string
            enabledCloudwatchLogsExports:
              items:
                type: string
              type: array
            endpoint:
              type: string
            engine:
              type: string
            engineVersion:
              type: string
            finalSnapshotIdentifier:
              type: string
            hostedZoneID:
              type: string
            iamDatabaseAuthenticationEnabled:
              type: boolean
            id:
              type: string
            identifier:
              type: string
            identifierPrefix:
              type: string
            instanceClass:
              type: string
            iops:
              format: int64
              type: integer
            kmsKeyID:
              type: string
            licenseModel:
              type: string
            maintenanceWindow:
              type: string
            maxAllocatedStorage:
              format: int64
              type: integer
            monitoringInterval:
              format: int64
              type: integer
            monitoringRoleArn:
              type: string
            multiAz:
              type: boolean
            name:
              type: string
            optionGroupName:
              type: string
            parameterGroupName:
              type: string
            performanceInsightsEnabled:
              type: boolean
            performanceInsightsKmsKeyID:
              type: string
            performanceInsightsRetentionPeriod:
              format: int64
              type: integer
            port:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publiclyAccessible:
              type: boolean
            replicas:
              items:
                type: string
              type: array
            replicateSourceDb:
              type: string
            resourceID:
              type: string
            s3Import:
              items:
                properties:
                  bucketName:
                    type: string
                  bucketPrefix:
                    type: string
                  ingestionRole:
                    type: string
                  sourceEngine:
                    type: string
                  sourceEngineVersion:
                    type: string
                required:
                - bucketName
                - ingestionRole
                - sourceEngine
                - sourceEngineVersion
                type: object
              maxItems: 1
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            securityGroupNames:
              items:
                type: string
              type: array
            skipFinalSnapshot:
              type: boolean
            snapshotIdentifier:
              type: string
            status:
              type: string
            storageEncrypted:
              type: boolean
            storageType:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            timezone:
              type: string
            username:
              type: string
            vpcSecurityGroupIDS:
              items:
                type: string
              type: array
          required:
          - instanceClass
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                address:
                  type: string
                allocatedStorage:
                  format: int64
                  type: integer
                allowMajorVersionUpgrade:
                  type: boolean
                applyImmediately:
                  type: boolean
                arn:
                  type: string
                autoMinorVersionUpgrade:
                  type: boolean
                availabilityZone:
                  type: string
                backupRetentionPeriod:
                  format: int64
                  type: integer
                backupWindow:
                  type: string
                caCertIdentifier:
                  type: string
                characterSetName:
                  type: string
                copyTagsToSnapshot:
                  type: boolean
                dbSubnetGroupName:
                  type: string
                deletionProtection:
                  type: boolean
                domain:
                  type: string
                domainIamRoleName:
                  type: string
                enabledCloudwatchLogsExports:
                  items:
                    type: string
                  type: array
                endpoint:
                  type: string
                engine:
                  type: string
                engineVersion:
                  type: string
                finalSnapshotIdentifier:
                  type: string
                hostedZoneID:
                  type: string
                iamDatabaseAuthenticationEnabled:
                  type: boolean
                id:
                  type: string
                identifier:
                  type: string
                identifierPrefix:
                  type: string
                instanceClass:
                  type: string
                iops:
                  format: int64
                  type: integer
                kmsKeyID:
                  type: string
                licenseModel:
                  type: string
                maintenanceWindow:
                  type: string
                maxAllocatedStorage:
                  format: int64
                  type: integer
                monitoringInterval:
                  format: int64
                  type: integer
                monitoringRoleArn:
                  type: string
                multiAz:
                  type: boolean
                name:
                  type: string
                optionGroupName:
                  type: string
                parameterGroupName:
                  type: string
                performanceInsightsEnabled:
                  type: boolean
                performanceInsightsKmsKeyID:
                  type: string
                performanceInsightsRetentionPeriod:
                  format: int64
                  type: integer
                port:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publiclyAccessible:
                  type: boolean
                replicas:
                  items:
                    type: string
                  type: array
                replicateSourceDb:
                  type: string
                resourceID:
                  type: string
                s3Import:
                  items:
                    properties:
                      bucketName:
                        type: string
                      bucketPrefix:
                        type: string
                      ingestionRole:
                        type: string
                      sourceEngine:
                        type: string
                      sourceEngineVersion:
                        type: string
                    required:
                    - bucketName
                    - ingestionRole
                    - sourceEngine
                    - sourceEngineVersion
                    type: object
                  maxItems: 1
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                securityGroupNames:
                  items:
                    type: string
                  type: array
                skipFinalSnapshot:
                  type: boolean
                snapshotIdentifier:
                  type: string
                status:
                  type: string
                storageEncrypted:
                  type: boolean
                storageType:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                timezone:
                  type: string
                username:
                  type: string
                vpcSecurityGroupIDS:
                  items:
                    type: string
                  type: array
              required:
              - instanceClass
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
