apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: spacesbucketobjects.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: SpacesBucketObject
    listKind: SpacesBucketObjectList
    plural: spacesbucketobjects
    singular: spacesbucketobject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            acl:
              type: string
            bucket:
              type: string
            cacheControl:
              type: string
            content:
              type: string
            contentBase64:
              type: string
            contentDisposition:
              type: string
            contentEncoding:
              type: string
            contentLanguage:
              type: string
            contentType:
              type: string
            etag:
              type: string
            forceDestroy:
              type: boolean
            id:
              type: string
            key:
              type: string
            metadata:
              additionalProperties:
                type: string
              type: object
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            source:
              type: string
            versionID:
              type: string
            websiteRedirect:
              type: string
          required:
          - bucket
          - key
          - providerRef
          - region
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                acl:
                  type: string
                bucket:
                  type: string
                cacheControl:
                  type: string
                content:
                  type: string
                contentBase64:
                  type: string
                contentDisposition:
                  type: string
                contentEncoding:
                  type: string
                contentLanguage:
                  type: string
                contentType:
                  type: string
                etag:
                  type: string
                forceDestroy:
                  type: boolean
                id:
                  type: string
                key:
                  type: string
                metadata:
                  additionalProperties:
                    type: string
                  type: object
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                source:
                  type: string
                versionID:
                  type: string
                websiteRedirect:
                  type: string
              required:
              - bucket
              - key
              - providerRef
              - region
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
