apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: containernodepools.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ContainerNodePool
    listKind: ContainerNodePoolList
    plural: containernodepools
    singular: containernodepool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoscaling:
              items:
                properties:
                  maxNodeCount:
                    format: int64
                    type: integer
                  minNodeCount:
                    format: int64
                    type: integer
                required:
                - maxNodeCount
                - minNodeCount
                type: object
              maxItems: 1
              type: array
            cluster:
              type: string
            id:
              type: string
            initialNodeCount:
              format: int64
              type: integer
            instanceGroupUrls:
              items:
                type: string
              type: array
            location:
              type: string
            management:
              items:
                properties:
                  autoRepair:
                    type: boolean
                  autoUpgrade:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            maxPodsPerNode:
              format: int64
              type: integer
            name:
              type: string
            namePrefix:
              type: string
            nodeConfig:
              items:
                properties:
                  diskSizeGb:
                    format: int64
                    type: integer
                  diskType:
                    type: string
                  guestAccelerator:
                    items:
                      properties:
                        count:
                          format: int64
                          type: integer
                        type:
                          type: string
                      required:
                      - count
                      - type
                      type: object
                    type: array
                  imageType:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  localSsdCount:
                    format: int64
                    type: integer
                  machineType:
                    type: string
                  metadata:
                    additionalProperties:
                      type: string
                    type: object
                  minCPUPlatform:
                    type: string
                  oauthScopes:
                    items:
                      type: string
                    type: array
                  preemptible:
                    type: boolean
                  serviceAccount:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                type: object
              maxItems: 1
              type: array
            nodeCount:
              format: int64
              type: integer
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: Deprecated
              type: string
            version:
              type: string
            zone:
              description: Deprecated
              type: string
          required:
          - cluster
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                autoscaling:
                  items:
                    properties:
                      maxNodeCount:
                        format: int64
                        type: integer
                      minNodeCount:
                        format: int64
                        type: integer
                    required:
                    - maxNodeCount
                    - minNodeCount
                    type: object
                  maxItems: 1
                  type: array
                cluster:
                  type: string
                id:
                  type: string
                initialNodeCount:
                  format: int64
                  type: integer
                instanceGroupUrls:
                  items:
                    type: string
                  type: array
                location:
                  type: string
                management:
                  items:
                    properties:
                      autoRepair:
                        type: boolean
                      autoUpgrade:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                maxPodsPerNode:
                  format: int64
                  type: integer
                name:
                  type: string
                namePrefix:
                  type: string
                nodeConfig:
                  items:
                    properties:
                      diskSizeGb:
                        format: int64
                        type: integer
                      diskType:
                        type: string
                      guestAccelerator:
                        items:
                          properties:
                            count:
                              format: int64
                              type: integer
                            type:
                              type: string
                          required:
                          - count
                          - type
                          type: object
                        type: array
                      imageType:
                        type: string
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      localSsdCount:
                        format: int64
                        type: integer
                      machineType:
                        type: string
                      metadata:
                        additionalProperties:
                          type: string
                        type: object
                      minCPUPlatform:
                        type: string
                      oauthScopes:
                        items:
                          type: string
                        type: array
                      preemptible:
                        type: boolean
                      serviceAccount:
                        type: string
                      tags:
                        items:
                          type: string
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                nodeCount:
                  format: int64
                  type: integer
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  description: Deprecated
                  type: string
                version:
                  type: string
                zone:
                  description: Deprecated
                  type: string
              required:
              - cluster
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
