/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/google/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKmsKeyRingIamPolicies implements KmsKeyRingIamPolicyInterface
type FakeKmsKeyRingIamPolicies struct {
	Fake *FakeGoogleV1alpha1
	ns   string
}

var kmskeyringiampoliciesResource = schema.GroupVersionResource{Group: "google.kubeform.com", Version: "v1alpha1", Resource: "kmskeyringiampolicies"}

var kmskeyringiampoliciesKind = schema.GroupVersionKind{Group: "google.kubeform.com", Version: "v1alpha1", Kind: "KmsKeyRingIamPolicy"}

// Get takes name of the kmsKeyRingIamPolicy, and returns the corresponding kmsKeyRingIamPolicy object, and an error if there is any.
func (c *FakeKmsKeyRingIamPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KmsKeyRingIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kmskeyringiampoliciesResource, c.ns, name), &v1alpha1.KmsKeyRingIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KmsKeyRingIamPolicy), err
}

// List takes label and field selectors, and returns the list of KmsKeyRingIamPolicies that match those selectors.
func (c *FakeKmsKeyRingIamPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KmsKeyRingIamPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kmskeyringiampoliciesResource, kmskeyringiampoliciesKind, c.ns, opts), &v1alpha1.KmsKeyRingIamPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KmsKeyRingIamPolicyList{ListMeta: obj.(*v1alpha1.KmsKeyRingIamPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.KmsKeyRingIamPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kmsKeyRingIamPolicies.
func (c *FakeKmsKeyRingIamPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kmskeyringiampoliciesResource, c.ns, opts))

}

// Create takes the representation of a kmsKeyRingIamPolicy and creates it.  Returns the server's representation of the kmsKeyRingIamPolicy, and an error, if there is any.
func (c *FakeKmsKeyRingIamPolicies) Create(ctx context.Context, kmsKeyRingIamPolicy *v1alpha1.KmsKeyRingIamPolicy, opts v1.CreateOptions) (result *v1alpha1.KmsKeyRingIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kmskeyringiampoliciesResource, c.ns, kmsKeyRingIamPolicy), &v1alpha1.KmsKeyRingIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KmsKeyRingIamPolicy), err
}

// Update takes the representation of a kmsKeyRingIamPolicy and updates it. Returns the server's representation of the kmsKeyRingIamPolicy, and an error, if there is any.
func (c *FakeKmsKeyRingIamPolicies) Update(ctx context.Context, kmsKeyRingIamPolicy *v1alpha1.KmsKeyRingIamPolicy, opts v1.UpdateOptions) (result *v1alpha1.KmsKeyRingIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kmskeyringiampoliciesResource, c.ns, kmsKeyRingIamPolicy), &v1alpha1.KmsKeyRingIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KmsKeyRingIamPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKmsKeyRingIamPolicies) UpdateStatus(ctx context.Context, kmsKeyRingIamPolicy *v1alpha1.KmsKeyRingIamPolicy, opts v1.UpdateOptions) (*v1alpha1.KmsKeyRingIamPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kmskeyringiampoliciesResource, "status", c.ns, kmsKeyRingIamPolicy), &v1alpha1.KmsKeyRingIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KmsKeyRingIamPolicy), err
}

// Delete takes name of the kmsKeyRingIamPolicy and deletes it. Returns an error if one occurs.
func (c *FakeKmsKeyRingIamPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kmskeyringiampoliciesResource, c.ns, name), &v1alpha1.KmsKeyRingIamPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKmsKeyRingIamPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kmskeyringiampoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KmsKeyRingIamPolicyList{})
	return err
}

// Patch applies the patch and returns the patched kmsKeyRingIamPolicy.
func (c *FakeKmsKeyRingIamPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KmsKeyRingIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kmskeyringiampoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.KmsKeyRingIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KmsKeyRingIamPolicy), err
}
