/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/google/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBigtableGcPolicies implements BigtableGcPolicyInterface
type FakeBigtableGcPolicies struct {
	Fake *FakeGoogleV1alpha1
	ns   string
}

var bigtablegcpoliciesResource = schema.GroupVersionResource{Group: "google.kubeform.com", Version: "v1alpha1", Resource: "bigtablegcpolicies"}

var bigtablegcpoliciesKind = schema.GroupVersionKind{Group: "google.kubeform.com", Version: "v1alpha1", Kind: "BigtableGcPolicy"}

// Get takes name of the bigtableGcPolicy, and returns the corresponding bigtableGcPolicy object, and an error if there is any.
func (c *FakeBigtableGcPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BigtableGcPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bigtablegcpoliciesResource, c.ns, name), &v1alpha1.BigtableGcPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BigtableGcPolicy), err
}

// List takes label and field selectors, and returns the list of BigtableGcPolicies that match those selectors.
func (c *FakeBigtableGcPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BigtableGcPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bigtablegcpoliciesResource, bigtablegcpoliciesKind, c.ns, opts), &v1alpha1.BigtableGcPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BigtableGcPolicyList{ListMeta: obj.(*v1alpha1.BigtableGcPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.BigtableGcPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bigtableGcPolicies.
func (c *FakeBigtableGcPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bigtablegcpoliciesResource, c.ns, opts))

}

// Create takes the representation of a bigtableGcPolicy and creates it.  Returns the server's representation of the bigtableGcPolicy, and an error, if there is any.
func (c *FakeBigtableGcPolicies) Create(ctx context.Context, bigtableGcPolicy *v1alpha1.BigtableGcPolicy, opts v1.CreateOptions) (result *v1alpha1.BigtableGcPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bigtablegcpoliciesResource, c.ns, bigtableGcPolicy), &v1alpha1.BigtableGcPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BigtableGcPolicy), err
}

// Update takes the representation of a bigtableGcPolicy and updates it. Returns the server's representation of the bigtableGcPolicy, and an error, if there is any.
func (c *FakeBigtableGcPolicies) Update(ctx context.Context, bigtableGcPolicy *v1alpha1.BigtableGcPolicy, opts v1.UpdateOptions) (result *v1alpha1.BigtableGcPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bigtablegcpoliciesResource, c.ns, bigtableGcPolicy), &v1alpha1.BigtableGcPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BigtableGcPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBigtableGcPolicies) UpdateStatus(ctx context.Context, bigtableGcPolicy *v1alpha1.BigtableGcPolicy, opts v1.UpdateOptions) (*v1alpha1.BigtableGcPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bigtablegcpoliciesResource, "status", c.ns, bigtableGcPolicy), &v1alpha1.BigtableGcPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BigtableGcPolicy), err
}

// Delete takes name of the bigtableGcPolicy and deletes it. Returns an error if one occurs.
func (c *FakeBigtableGcPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bigtablegcpoliciesResource, c.ns, name), &v1alpha1.BigtableGcPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBigtableGcPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bigtablegcpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BigtableGcPolicyList{})
	return err
}

// Patch applies the patch and returns the patched bigtableGcPolicy.
func (c *FakeBigtableGcPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BigtableGcPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bigtablegcpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BigtableGcPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BigtableGcPolicy), err
}
