/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/google/v1alpha1"
)

// FakeComputeTargetHttpProxies implements ComputeTargetHttpProxyInterface
type FakeComputeTargetHttpProxies struct {
	Fake *FakeGoogleV1alpha1
}

var computetargethttpproxiesResource = schema.GroupVersionResource{Group: "google.kubeform.com", Version: "v1alpha1", Resource: "computetargethttpproxies"}

var computetargethttpproxiesKind = schema.GroupVersionKind{Group: "google.kubeform.com", Version: "v1alpha1", Kind: "ComputeTargetHttpProxy"}

// Get takes name of the computeTargetHttpProxy, and returns the corresponding computeTargetHttpProxy object, and an error if there is any.
func (c *FakeComputeTargetHttpProxies) Get(name string, options v1.GetOptions) (result *v1alpha1.ComputeTargetHttpProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(computetargethttpproxiesResource, name), &v1alpha1.ComputeTargetHttpProxy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeTargetHttpProxy), err
}

// List takes label and field selectors, and returns the list of ComputeTargetHttpProxies that match those selectors.
func (c *FakeComputeTargetHttpProxies) List(opts v1.ListOptions) (result *v1alpha1.ComputeTargetHttpProxyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(computetargethttpproxiesResource, computetargethttpproxiesKind, opts), &v1alpha1.ComputeTargetHttpProxyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ComputeTargetHttpProxyList{ListMeta: obj.(*v1alpha1.ComputeTargetHttpProxyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ComputeTargetHttpProxyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested computeTargetHttpProxies.
func (c *FakeComputeTargetHttpProxies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(computetargethttpproxiesResource, opts))
}

// Create takes the representation of a computeTargetHttpProxy and creates it.  Returns the server's representation of the computeTargetHttpProxy, and an error, if there is any.
func (c *FakeComputeTargetHttpProxies) Create(computeTargetHttpProxy *v1alpha1.ComputeTargetHttpProxy) (result *v1alpha1.ComputeTargetHttpProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(computetargethttpproxiesResource, computeTargetHttpProxy), &v1alpha1.ComputeTargetHttpProxy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeTargetHttpProxy), err
}

// Update takes the representation of a computeTargetHttpProxy and updates it. Returns the server's representation of the computeTargetHttpProxy, and an error, if there is any.
func (c *FakeComputeTargetHttpProxies) Update(computeTargetHttpProxy *v1alpha1.ComputeTargetHttpProxy) (result *v1alpha1.ComputeTargetHttpProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(computetargethttpproxiesResource, computeTargetHttpProxy), &v1alpha1.ComputeTargetHttpProxy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeTargetHttpProxy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeComputeTargetHttpProxies) UpdateStatus(computeTargetHttpProxy *v1alpha1.ComputeTargetHttpProxy) (*v1alpha1.ComputeTargetHttpProxy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(computetargethttpproxiesResource, "status", computeTargetHttpProxy), &v1alpha1.ComputeTargetHttpProxy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeTargetHttpProxy), err
}

// Delete takes name of the computeTargetHttpProxy and deletes it. Returns an error if one occurs.
func (c *FakeComputeTargetHttpProxies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(computetargethttpproxiesResource, name), &v1alpha1.ComputeTargetHttpProxy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComputeTargetHttpProxies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(computetargethttpproxiesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ComputeTargetHttpProxyList{})
	return err
}

// Patch applies the patch and returns the patched computeTargetHttpProxy.
func (c *FakeComputeTargetHttpProxies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ComputeTargetHttpProxy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(computetargethttpproxiesResource, name, pt, data, subresources...), &v1alpha1.ComputeTargetHttpProxy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeTargetHttpProxy), err
}
