/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/google/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIapAppEngineVersionIamPolicies implements IapAppEngineVersionIamPolicyInterface
type FakeIapAppEngineVersionIamPolicies struct {
	Fake *FakeGoogleV1alpha1
	ns   string
}

var iapappengineversioniampoliciesResource = schema.GroupVersionResource{Group: "google.kubeform.com", Version: "v1alpha1", Resource: "iapappengineversioniampolicies"}

var iapappengineversioniampoliciesKind = schema.GroupVersionKind{Group: "google.kubeform.com", Version: "v1alpha1", Kind: "IapAppEngineVersionIamPolicy"}

// Get takes name of the iapAppEngineVersionIamPolicy, and returns the corresponding iapAppEngineVersionIamPolicy object, and an error if there is any.
func (c *FakeIapAppEngineVersionIamPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IapAppEngineVersionIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(iapappengineversioniampoliciesResource, c.ns, name), &v1alpha1.IapAppEngineVersionIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IapAppEngineVersionIamPolicy), err
}

// List takes label and field selectors, and returns the list of IapAppEngineVersionIamPolicies that match those selectors.
func (c *FakeIapAppEngineVersionIamPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IapAppEngineVersionIamPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(iapappengineversioniampoliciesResource, iapappengineversioniampoliciesKind, c.ns, opts), &v1alpha1.IapAppEngineVersionIamPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IapAppEngineVersionIamPolicyList{ListMeta: obj.(*v1alpha1.IapAppEngineVersionIamPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.IapAppEngineVersionIamPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iapAppEngineVersionIamPolicies.
func (c *FakeIapAppEngineVersionIamPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(iapappengineversioniampoliciesResource, c.ns, opts))

}

// Create takes the representation of a iapAppEngineVersionIamPolicy and creates it.  Returns the server's representation of the iapAppEngineVersionIamPolicy, and an error, if there is any.
func (c *FakeIapAppEngineVersionIamPolicies) Create(ctx context.Context, iapAppEngineVersionIamPolicy *v1alpha1.IapAppEngineVersionIamPolicy, opts v1.CreateOptions) (result *v1alpha1.IapAppEngineVersionIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(iapappengineversioniampoliciesResource, c.ns, iapAppEngineVersionIamPolicy), &v1alpha1.IapAppEngineVersionIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IapAppEngineVersionIamPolicy), err
}

// Update takes the representation of a iapAppEngineVersionIamPolicy and updates it. Returns the server's representation of the iapAppEngineVersionIamPolicy, and an error, if there is any.
func (c *FakeIapAppEngineVersionIamPolicies) Update(ctx context.Context, iapAppEngineVersionIamPolicy *v1alpha1.IapAppEngineVersionIamPolicy, opts v1.UpdateOptions) (result *v1alpha1.IapAppEngineVersionIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(iapappengineversioniampoliciesResource, c.ns, iapAppEngineVersionIamPolicy), &v1alpha1.IapAppEngineVersionIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IapAppEngineVersionIamPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIapAppEngineVersionIamPolicies) UpdateStatus(ctx context.Context, iapAppEngineVersionIamPolicy *v1alpha1.IapAppEngineVersionIamPolicy, opts v1.UpdateOptions) (*v1alpha1.IapAppEngineVersionIamPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(iapappengineversioniampoliciesResource, "status", c.ns, iapAppEngineVersionIamPolicy), &v1alpha1.IapAppEngineVersionIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IapAppEngineVersionIamPolicy), err
}

// Delete takes name of the iapAppEngineVersionIamPolicy and deletes it. Returns an error if one occurs.
func (c *FakeIapAppEngineVersionIamPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(iapappengineversioniampoliciesResource, c.ns, name), &v1alpha1.IapAppEngineVersionIamPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIapAppEngineVersionIamPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(iapappengineversioniampoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IapAppEngineVersionIamPolicyList{})
	return err
}

// Patch applies the patch and returns the patched iapAppEngineVersionIamPolicy.
func (c *FakeIapAppEngineVersionIamPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IapAppEngineVersionIamPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(iapappengineversioniampoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IapAppEngineVersionIamPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IapAppEngineVersionIamPolicy), err
}
