/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/google/v1alpha1"
)

// FakeComputeUrlMaps implements ComputeUrlMapInterface
type FakeComputeUrlMaps struct {
	Fake *FakeGoogleV1alpha1
}

var computeurlmapsResource = schema.GroupVersionResource{Group: "google.kubeform.com", Version: "v1alpha1", Resource: "computeurlmaps"}

var computeurlmapsKind = schema.GroupVersionKind{Group: "google.kubeform.com", Version: "v1alpha1", Kind: "ComputeUrlMap"}

// Get takes name of the computeUrlMap, and returns the corresponding computeUrlMap object, and an error if there is any.
func (c *FakeComputeUrlMaps) Get(name string, options v1.GetOptions) (result *v1alpha1.ComputeUrlMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(computeurlmapsResource, name), &v1alpha1.ComputeUrlMap{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeUrlMap), err
}

// List takes label and field selectors, and returns the list of ComputeUrlMaps that match those selectors.
func (c *FakeComputeUrlMaps) List(opts v1.ListOptions) (result *v1alpha1.ComputeUrlMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(computeurlmapsResource, computeurlmapsKind, opts), &v1alpha1.ComputeUrlMapList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ComputeUrlMapList{ListMeta: obj.(*v1alpha1.ComputeUrlMapList).ListMeta}
	for _, item := range obj.(*v1alpha1.ComputeUrlMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested computeUrlMaps.
func (c *FakeComputeUrlMaps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(computeurlmapsResource, opts))
}

// Create takes the representation of a computeUrlMap and creates it.  Returns the server's representation of the computeUrlMap, and an error, if there is any.
func (c *FakeComputeUrlMaps) Create(computeUrlMap *v1alpha1.ComputeUrlMap) (result *v1alpha1.ComputeUrlMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(computeurlmapsResource, computeUrlMap), &v1alpha1.ComputeUrlMap{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeUrlMap), err
}

// Update takes the representation of a computeUrlMap and updates it. Returns the server's representation of the computeUrlMap, and an error, if there is any.
func (c *FakeComputeUrlMaps) Update(computeUrlMap *v1alpha1.ComputeUrlMap) (result *v1alpha1.ComputeUrlMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(computeurlmapsResource, computeUrlMap), &v1alpha1.ComputeUrlMap{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeUrlMap), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeComputeUrlMaps) UpdateStatus(computeUrlMap *v1alpha1.ComputeUrlMap) (*v1alpha1.ComputeUrlMap, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(computeurlmapsResource, "status", computeUrlMap), &v1alpha1.ComputeUrlMap{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeUrlMap), err
}

// Delete takes name of the computeUrlMap and deletes it. Returns an error if one occurs.
func (c *FakeComputeUrlMaps) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(computeurlmapsResource, name), &v1alpha1.ComputeUrlMap{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComputeUrlMaps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(computeurlmapsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ComputeUrlMapList{})
	return err
}

// Patch applies the patch and returns the patched computeUrlMap.
func (c *FakeComputeUrlMaps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ComputeUrlMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(computeurlmapsResource, name, pt, data, subresources...), &v1alpha1.ComputeUrlMap{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ComputeUrlMap), err
}
