/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// AzurermPrivateDnsZonesGetter has a method to return a AzurermPrivateDnsZoneInterface.
// A group's client should implement this interface.
type AzurermPrivateDnsZonesGetter interface {
	AzurermPrivateDnsZones() AzurermPrivateDnsZoneInterface
}

// AzurermPrivateDnsZoneInterface has methods to work with AzurermPrivateDnsZone resources.
type AzurermPrivateDnsZoneInterface interface {
	Create(*v1alpha1.AzurermPrivateDnsZone) (*v1alpha1.AzurermPrivateDnsZone, error)
	Update(*v1alpha1.AzurermPrivateDnsZone) (*v1alpha1.AzurermPrivateDnsZone, error)
	UpdateStatus(*v1alpha1.AzurermPrivateDnsZone) (*v1alpha1.AzurermPrivateDnsZone, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AzurermPrivateDnsZone, error)
	List(opts v1.ListOptions) (*v1alpha1.AzurermPrivateDnsZoneList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzurermPrivateDnsZone, err error)
	AzurermPrivateDnsZoneExpansion
}

// azurermPrivateDnsZones implements AzurermPrivateDnsZoneInterface
type azurermPrivateDnsZones struct {
	client rest.Interface
}

// newAzurermPrivateDnsZones returns a AzurermPrivateDnsZones
func newAzurermPrivateDnsZones(c *AzurermV1alpha1Client) *azurermPrivateDnsZones {
	return &azurermPrivateDnsZones{
		client: c.RESTClient(),
	}
}

// Get takes name of the azurermPrivateDnsZone, and returns the corresponding azurermPrivateDnsZone object, and an error if there is any.
func (c *azurermPrivateDnsZones) Get(name string, options v1.GetOptions) (result *v1alpha1.AzurermPrivateDnsZone, err error) {
	result = &v1alpha1.AzurermPrivateDnsZone{}
	err = c.client.Get().
		Resource("azurermprivatednszones").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzurermPrivateDnsZones that match those selectors.
func (c *azurermPrivateDnsZones) List(opts v1.ListOptions) (result *v1alpha1.AzurermPrivateDnsZoneList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AzurermPrivateDnsZoneList{}
	err = c.client.Get().
		Resource("azurermprivatednszones").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azurermPrivateDnsZones.
func (c *azurermPrivateDnsZones) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("azurermprivatednszones").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azurermPrivateDnsZone and creates it.  Returns the server's representation of the azurermPrivateDnsZone, and an error, if there is any.
func (c *azurermPrivateDnsZones) Create(azurermPrivateDnsZone *v1alpha1.AzurermPrivateDnsZone) (result *v1alpha1.AzurermPrivateDnsZone, err error) {
	result = &v1alpha1.AzurermPrivateDnsZone{}
	err = c.client.Post().
		Resource("azurermprivatednszones").
		Body(azurermPrivateDnsZone).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azurermPrivateDnsZone and updates it. Returns the server's representation of the azurermPrivateDnsZone, and an error, if there is any.
func (c *azurermPrivateDnsZones) Update(azurermPrivateDnsZone *v1alpha1.AzurermPrivateDnsZone) (result *v1alpha1.AzurermPrivateDnsZone, err error) {
	result = &v1alpha1.AzurermPrivateDnsZone{}
	err = c.client.Put().
		Resource("azurermprivatednszones").
		Name(azurermPrivateDnsZone.Name).
		Body(azurermPrivateDnsZone).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *azurermPrivateDnsZones) UpdateStatus(azurermPrivateDnsZone *v1alpha1.AzurermPrivateDnsZone) (result *v1alpha1.AzurermPrivateDnsZone, err error) {
	result = &v1alpha1.AzurermPrivateDnsZone{}
	err = c.client.Put().
		Resource("azurermprivatednszones").
		Name(azurermPrivateDnsZone.Name).
		SubResource("status").
		Body(azurermPrivateDnsZone).
		Do().
		Into(result)
	return
}

// Delete takes name of the azurermPrivateDnsZone and deletes it. Returns an error if one occurs.
func (c *azurermPrivateDnsZones) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("azurermprivatednszones").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azurermPrivateDnsZones) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("azurermprivatednszones").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azurermPrivateDnsZone.
func (c *azurermPrivateDnsZones) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzurermPrivateDnsZone, err error) {
	result = &v1alpha1.AzurermPrivateDnsZone{}
	err = c.client.Patch(pt).
		Resource("azurermprivatednszones").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
