/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFmsAdminAccounts implements FmsAdminAccountInterface
type FakeFmsAdminAccounts struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var fmsadminaccountsResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "fmsadminaccounts"}

var fmsadminaccountsKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "FmsAdminAccount"}

// Get takes name of the fmsAdminAccount, and returns the corresponding fmsAdminAccount object, and an error if there is any.
func (c *FakeFmsAdminAccounts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FmsAdminAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fmsadminaccountsResource, c.ns, name), &v1alpha1.FmsAdminAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FmsAdminAccount), err
}

// List takes label and field selectors, and returns the list of FmsAdminAccounts that match those selectors.
func (c *FakeFmsAdminAccounts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FmsAdminAccountList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fmsadminaccountsResource, fmsadminaccountsKind, c.ns, opts), &v1alpha1.FmsAdminAccountList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FmsAdminAccountList{ListMeta: obj.(*v1alpha1.FmsAdminAccountList).ListMeta}
	for _, item := range obj.(*v1alpha1.FmsAdminAccountList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fmsAdminAccounts.
func (c *FakeFmsAdminAccounts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fmsadminaccountsResource, c.ns, opts))

}

// Create takes the representation of a fmsAdminAccount and creates it.  Returns the server's representation of the fmsAdminAccount, and an error, if there is any.
func (c *FakeFmsAdminAccounts) Create(ctx context.Context, fmsAdminAccount *v1alpha1.FmsAdminAccount, opts v1.CreateOptions) (result *v1alpha1.FmsAdminAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fmsadminaccountsResource, c.ns, fmsAdminAccount), &v1alpha1.FmsAdminAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FmsAdminAccount), err
}

// Update takes the representation of a fmsAdminAccount and updates it. Returns the server's representation of the fmsAdminAccount, and an error, if there is any.
func (c *FakeFmsAdminAccounts) Update(ctx context.Context, fmsAdminAccount *v1alpha1.FmsAdminAccount, opts v1.UpdateOptions) (result *v1alpha1.FmsAdminAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fmsadminaccountsResource, c.ns, fmsAdminAccount), &v1alpha1.FmsAdminAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FmsAdminAccount), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFmsAdminAccounts) UpdateStatus(ctx context.Context, fmsAdminAccount *v1alpha1.FmsAdminAccount, opts v1.UpdateOptions) (*v1alpha1.FmsAdminAccount, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fmsadminaccountsResource, "status", c.ns, fmsAdminAccount), &v1alpha1.FmsAdminAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FmsAdminAccount), err
}

// Delete takes name of the fmsAdminAccount and deletes it. Returns an error if one occurs.
func (c *FakeFmsAdminAccounts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fmsadminaccountsResource, c.ns, name), &v1alpha1.FmsAdminAccount{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFmsAdminAccounts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fmsadminaccountsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FmsAdminAccountList{})
	return err
}

// Patch applies the patch and returns the patched fmsAdminAccount.
func (c *FakeFmsAdminAccounts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FmsAdminAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fmsadminaccountsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FmsAdminAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FmsAdminAccount), err
}
