/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDynamodbTables implements DynamodbTableInterface
type FakeDynamodbTables struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var dynamodbtablesResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "dynamodbtables"}

var dynamodbtablesKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "DynamodbTable"}

// Get takes name of the dynamodbTable, and returns the corresponding dynamodbTable object, and an error if there is any.
func (c *FakeDynamodbTables) Get(name string, options v1.GetOptions) (result *v1alpha1.DynamodbTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dynamodbtablesResource, c.ns, name), &v1alpha1.DynamodbTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DynamodbTable), err
}

// List takes label and field selectors, and returns the list of DynamodbTables that match those selectors.
func (c *FakeDynamodbTables) List(opts v1.ListOptions) (result *v1alpha1.DynamodbTableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dynamodbtablesResource, dynamodbtablesKind, c.ns, opts), &v1alpha1.DynamodbTableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DynamodbTableList{ListMeta: obj.(*v1alpha1.DynamodbTableList).ListMeta}
	for _, item := range obj.(*v1alpha1.DynamodbTableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dynamodbTables.
func (c *FakeDynamodbTables) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dynamodbtablesResource, c.ns, opts))

}

// Create takes the representation of a dynamodbTable and creates it.  Returns the server's representation of the dynamodbTable, and an error, if there is any.
func (c *FakeDynamodbTables) Create(dynamodbTable *v1alpha1.DynamodbTable) (result *v1alpha1.DynamodbTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dynamodbtablesResource, c.ns, dynamodbTable), &v1alpha1.DynamodbTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DynamodbTable), err
}

// Update takes the representation of a dynamodbTable and updates it. Returns the server's representation of the dynamodbTable, and an error, if there is any.
func (c *FakeDynamodbTables) Update(dynamodbTable *v1alpha1.DynamodbTable) (result *v1alpha1.DynamodbTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dynamodbtablesResource, c.ns, dynamodbTable), &v1alpha1.DynamodbTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DynamodbTable), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDynamodbTables) UpdateStatus(dynamodbTable *v1alpha1.DynamodbTable) (*v1alpha1.DynamodbTable, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dynamodbtablesResource, "status", c.ns, dynamodbTable), &v1alpha1.DynamodbTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DynamodbTable), err
}

// Delete takes name of the dynamodbTable and deletes it. Returns an error if one occurs.
func (c *FakeDynamodbTables) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dynamodbtablesResource, c.ns, name), &v1alpha1.DynamodbTable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDynamodbTables) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dynamodbtablesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DynamodbTableList{})
	return err
}

// Patch applies the patch and returns the patched dynamodbTable.
func (c *FakeDynamodbTables) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DynamodbTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dynamodbtablesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DynamodbTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DynamodbTable), err
}
