/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDmsReplicationInstances implements DmsReplicationInstanceInterface
type FakeDmsReplicationInstances struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var dmsreplicationinstancesResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "dmsreplicationinstances"}

var dmsreplicationinstancesKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "DmsReplicationInstance"}

// Get takes name of the dmsReplicationInstance, and returns the corresponding dmsReplicationInstance object, and an error if there is any.
func (c *FakeDmsReplicationInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.DmsReplicationInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dmsreplicationinstancesResource, c.ns, name), &v1alpha1.DmsReplicationInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DmsReplicationInstance), err
}

// List takes label and field selectors, and returns the list of DmsReplicationInstances that match those selectors.
func (c *FakeDmsReplicationInstances) List(opts v1.ListOptions) (result *v1alpha1.DmsReplicationInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dmsreplicationinstancesResource, dmsreplicationinstancesKind, c.ns, opts), &v1alpha1.DmsReplicationInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DmsReplicationInstanceList{ListMeta: obj.(*v1alpha1.DmsReplicationInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.DmsReplicationInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dmsReplicationInstances.
func (c *FakeDmsReplicationInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dmsreplicationinstancesResource, c.ns, opts))

}

// Create takes the representation of a dmsReplicationInstance and creates it.  Returns the server's representation of the dmsReplicationInstance, and an error, if there is any.
func (c *FakeDmsReplicationInstances) Create(dmsReplicationInstance *v1alpha1.DmsReplicationInstance) (result *v1alpha1.DmsReplicationInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dmsreplicationinstancesResource, c.ns, dmsReplicationInstance), &v1alpha1.DmsReplicationInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DmsReplicationInstance), err
}

// Update takes the representation of a dmsReplicationInstance and updates it. Returns the server's representation of the dmsReplicationInstance, and an error, if there is any.
func (c *FakeDmsReplicationInstances) Update(dmsReplicationInstance *v1alpha1.DmsReplicationInstance) (result *v1alpha1.DmsReplicationInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dmsreplicationinstancesResource, c.ns, dmsReplicationInstance), &v1alpha1.DmsReplicationInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DmsReplicationInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDmsReplicationInstances) UpdateStatus(dmsReplicationInstance *v1alpha1.DmsReplicationInstance) (*v1alpha1.DmsReplicationInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dmsreplicationinstancesResource, "status", c.ns, dmsReplicationInstance), &v1alpha1.DmsReplicationInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DmsReplicationInstance), err
}

// Delete takes name of the dmsReplicationInstance and deletes it. Returns an error if one occurs.
func (c *FakeDmsReplicationInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dmsreplicationinstancesResource, c.ns, name), &v1alpha1.DmsReplicationInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDmsReplicationInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dmsreplicationinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DmsReplicationInstanceList{})
	return err
}

// Patch applies the patch and returns the patched dmsReplicationInstance.
func (c *FakeDmsReplicationInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DmsReplicationInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dmsreplicationinstancesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DmsReplicationInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DmsReplicationInstance), err
}
