/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConfigConfigurationRecorders implements ConfigConfigurationRecorderInterface
type FakeConfigConfigurationRecorders struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var configconfigurationrecordersResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "configconfigurationrecorders"}

var configconfigurationrecordersKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "ConfigConfigurationRecorder"}

// Get takes name of the configConfigurationRecorder, and returns the corresponding configConfigurationRecorder object, and an error if there is any.
func (c *FakeConfigConfigurationRecorders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConfigConfigurationRecorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(configconfigurationrecordersResource, c.ns, name), &v1alpha1.ConfigConfigurationRecorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigConfigurationRecorder), err
}

// List takes label and field selectors, and returns the list of ConfigConfigurationRecorders that match those selectors.
func (c *FakeConfigConfigurationRecorders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConfigConfigurationRecorderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(configconfigurationrecordersResource, configconfigurationrecordersKind, c.ns, opts), &v1alpha1.ConfigConfigurationRecorderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConfigConfigurationRecorderList{ListMeta: obj.(*v1alpha1.ConfigConfigurationRecorderList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConfigConfigurationRecorderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested configConfigurationRecorders.
func (c *FakeConfigConfigurationRecorders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(configconfigurationrecordersResource, c.ns, opts))

}

// Create takes the representation of a configConfigurationRecorder and creates it.  Returns the server's representation of the configConfigurationRecorder, and an error, if there is any.
func (c *FakeConfigConfigurationRecorders) Create(ctx context.Context, configConfigurationRecorder *v1alpha1.ConfigConfigurationRecorder, opts v1.CreateOptions) (result *v1alpha1.ConfigConfigurationRecorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(configconfigurationrecordersResource, c.ns, configConfigurationRecorder), &v1alpha1.ConfigConfigurationRecorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigConfigurationRecorder), err
}

// Update takes the representation of a configConfigurationRecorder and updates it. Returns the server's representation of the configConfigurationRecorder, and an error, if there is any.
func (c *FakeConfigConfigurationRecorders) Update(ctx context.Context, configConfigurationRecorder *v1alpha1.ConfigConfigurationRecorder, opts v1.UpdateOptions) (result *v1alpha1.ConfigConfigurationRecorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(configconfigurationrecordersResource, c.ns, configConfigurationRecorder), &v1alpha1.ConfigConfigurationRecorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigConfigurationRecorder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConfigConfigurationRecorders) UpdateStatus(ctx context.Context, configConfigurationRecorder *v1alpha1.ConfigConfigurationRecorder, opts v1.UpdateOptions) (*v1alpha1.ConfigConfigurationRecorder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(configconfigurationrecordersResource, "status", c.ns, configConfigurationRecorder), &v1alpha1.ConfigConfigurationRecorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigConfigurationRecorder), err
}

// Delete takes name of the configConfigurationRecorder and deletes it. Returns an error if one occurs.
func (c *FakeConfigConfigurationRecorders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(configconfigurationrecordersResource, c.ns, name), &v1alpha1.ConfigConfigurationRecorder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConfigConfigurationRecorders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(configconfigurationrecordersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConfigConfigurationRecorderList{})
	return err
}

// Patch applies the patch and returns the patched configConfigurationRecorder.
func (c *FakeConfigConfigurationRecorders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConfigConfigurationRecorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(configconfigurationrecordersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConfigConfigurationRecorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConfigConfigurationRecorder), err
}
