/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSsmResourceDataSyncs implements SsmResourceDataSyncInterface
type FakeSsmResourceDataSyncs struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var ssmresourcedatasyncsResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "ssmresourcedatasyncs"}

var ssmresourcedatasyncsKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "SsmResourceDataSync"}

// Get takes name of the ssmResourceDataSync, and returns the corresponding ssmResourceDataSync object, and an error if there is any.
func (c *FakeSsmResourceDataSyncs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SsmResourceDataSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ssmresourcedatasyncsResource, c.ns, name), &v1alpha1.SsmResourceDataSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsmResourceDataSync), err
}

// List takes label and field selectors, and returns the list of SsmResourceDataSyncs that match those selectors.
func (c *FakeSsmResourceDataSyncs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SsmResourceDataSyncList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ssmresourcedatasyncsResource, ssmresourcedatasyncsKind, c.ns, opts), &v1alpha1.SsmResourceDataSyncList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SsmResourceDataSyncList{ListMeta: obj.(*v1alpha1.SsmResourceDataSyncList).ListMeta}
	for _, item := range obj.(*v1alpha1.SsmResourceDataSyncList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ssmResourceDataSyncs.
func (c *FakeSsmResourceDataSyncs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ssmresourcedatasyncsResource, c.ns, opts))

}

// Create takes the representation of a ssmResourceDataSync and creates it.  Returns the server's representation of the ssmResourceDataSync, and an error, if there is any.
func (c *FakeSsmResourceDataSyncs) Create(ctx context.Context, ssmResourceDataSync *v1alpha1.SsmResourceDataSync, opts v1.CreateOptions) (result *v1alpha1.SsmResourceDataSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ssmresourcedatasyncsResource, c.ns, ssmResourceDataSync), &v1alpha1.SsmResourceDataSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsmResourceDataSync), err
}

// Update takes the representation of a ssmResourceDataSync and updates it. Returns the server's representation of the ssmResourceDataSync, and an error, if there is any.
func (c *FakeSsmResourceDataSyncs) Update(ctx context.Context, ssmResourceDataSync *v1alpha1.SsmResourceDataSync, opts v1.UpdateOptions) (result *v1alpha1.SsmResourceDataSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ssmresourcedatasyncsResource, c.ns, ssmResourceDataSync), &v1alpha1.SsmResourceDataSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsmResourceDataSync), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSsmResourceDataSyncs) UpdateStatus(ctx context.Context, ssmResourceDataSync *v1alpha1.SsmResourceDataSync, opts v1.UpdateOptions) (*v1alpha1.SsmResourceDataSync, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ssmresourcedatasyncsResource, "status", c.ns, ssmResourceDataSync), &v1alpha1.SsmResourceDataSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsmResourceDataSync), err
}

// Delete takes name of the ssmResourceDataSync and deletes it. Returns an error if one occurs.
func (c *FakeSsmResourceDataSyncs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ssmresourcedatasyncsResource, c.ns, name), &v1alpha1.SsmResourceDataSync{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSsmResourceDataSyncs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ssmresourcedatasyncsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SsmResourceDataSyncList{})
	return err
}

// Patch applies the patch and returns the patched ssmResourceDataSync.
func (c *FakeSsmResourceDataSyncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SsmResourceDataSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ssmresourcedatasyncsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SsmResourceDataSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsmResourceDataSync), err
}
