/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCognitoIdentityPools implements CognitoIdentityPoolInterface
type FakeCognitoIdentityPools struct {
	Fake *FakeAwsV1alpha1
	ns   string
}

var cognitoidentitypoolsResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "cognitoidentitypools"}

var cognitoidentitypoolsKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "CognitoIdentityPool"}

// Get takes name of the cognitoIdentityPool, and returns the corresponding cognitoIdentityPool object, and an error if there is any.
func (c *FakeCognitoIdentityPools) Get(name string, options v1.GetOptions) (result *v1alpha1.CognitoIdentityPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cognitoidentitypoolsResource, c.ns, name), &v1alpha1.CognitoIdentityPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CognitoIdentityPool), err
}

// List takes label and field selectors, and returns the list of CognitoIdentityPools that match those selectors.
func (c *FakeCognitoIdentityPools) List(opts v1.ListOptions) (result *v1alpha1.CognitoIdentityPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cognitoidentitypoolsResource, cognitoidentitypoolsKind, c.ns, opts), &v1alpha1.CognitoIdentityPoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CognitoIdentityPoolList{ListMeta: obj.(*v1alpha1.CognitoIdentityPoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.CognitoIdentityPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cognitoIdentityPools.
func (c *FakeCognitoIdentityPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cognitoidentitypoolsResource, c.ns, opts))

}

// Create takes the representation of a cognitoIdentityPool and creates it.  Returns the server's representation of the cognitoIdentityPool, and an error, if there is any.
func (c *FakeCognitoIdentityPools) Create(cognitoIdentityPool *v1alpha1.CognitoIdentityPool) (result *v1alpha1.CognitoIdentityPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cognitoidentitypoolsResource, c.ns, cognitoIdentityPool), &v1alpha1.CognitoIdentityPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CognitoIdentityPool), err
}

// Update takes the representation of a cognitoIdentityPool and updates it. Returns the server's representation of the cognitoIdentityPool, and an error, if there is any.
func (c *FakeCognitoIdentityPools) Update(cognitoIdentityPool *v1alpha1.CognitoIdentityPool) (result *v1alpha1.CognitoIdentityPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cognitoidentitypoolsResource, c.ns, cognitoIdentityPool), &v1alpha1.CognitoIdentityPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CognitoIdentityPool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCognitoIdentityPools) UpdateStatus(cognitoIdentityPool *v1alpha1.CognitoIdentityPool) (*v1alpha1.CognitoIdentityPool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cognitoidentitypoolsResource, "status", c.ns, cognitoIdentityPool), &v1alpha1.CognitoIdentityPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CognitoIdentityPool), err
}

// Delete takes name of the cognitoIdentityPool and deletes it. Returns an error if one occurs.
func (c *FakeCognitoIdentityPools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cognitoidentitypoolsResource, c.ns, name), &v1alpha1.CognitoIdentityPool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCognitoIdentityPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cognitoidentitypoolsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CognitoIdentityPoolList{})
	return err
}

// Patch applies the patch and returns the patched cognitoIdentityPool.
func (c *FakeCognitoIdentityPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CognitoIdentityPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cognitoidentitypoolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CognitoIdentityPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CognitoIdentityPool), err
}
