/*
Copyright 2019 The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/aws/v1alpha1"
)

// FakeAwsSesIdentityPolicies implements AwsSesIdentityPolicyInterface
type FakeAwsSesIdentityPolicies struct {
	Fake *FakeAwsV1alpha1
}

var awssesidentitypoliciesResource = schema.GroupVersionResource{Group: "aws.kubeform.com", Version: "v1alpha1", Resource: "awssesidentitypolicies"}

var awssesidentitypoliciesKind = schema.GroupVersionKind{Group: "aws.kubeform.com", Version: "v1alpha1", Kind: "AwsSesIdentityPolicy"}

// Get takes name of the awsSesIdentityPolicy, and returns the corresponding awsSesIdentityPolicy object, and an error if there is any.
func (c *FakeAwsSesIdentityPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.AwsSesIdentityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(awssesidentitypoliciesResource, name), &v1alpha1.AwsSesIdentityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsSesIdentityPolicy), err
}

// List takes label and field selectors, and returns the list of AwsSesIdentityPolicies that match those selectors.
func (c *FakeAwsSesIdentityPolicies) List(opts v1.ListOptions) (result *v1alpha1.AwsSesIdentityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(awssesidentitypoliciesResource, awssesidentitypoliciesKind, opts), &v1alpha1.AwsSesIdentityPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsSesIdentityPolicyList{ListMeta: obj.(*v1alpha1.AwsSesIdentityPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.AwsSesIdentityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsSesIdentityPolicies.
func (c *FakeAwsSesIdentityPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(awssesidentitypoliciesResource, opts))
}

// Create takes the representation of a awsSesIdentityPolicy and creates it.  Returns the server's representation of the awsSesIdentityPolicy, and an error, if there is any.
func (c *FakeAwsSesIdentityPolicies) Create(awsSesIdentityPolicy *v1alpha1.AwsSesIdentityPolicy) (result *v1alpha1.AwsSesIdentityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(awssesidentitypoliciesResource, awsSesIdentityPolicy), &v1alpha1.AwsSesIdentityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsSesIdentityPolicy), err
}

// Update takes the representation of a awsSesIdentityPolicy and updates it. Returns the server's representation of the awsSesIdentityPolicy, and an error, if there is any.
func (c *FakeAwsSesIdentityPolicies) Update(awsSesIdentityPolicy *v1alpha1.AwsSesIdentityPolicy) (result *v1alpha1.AwsSesIdentityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(awssesidentitypoliciesResource, awsSesIdentityPolicy), &v1alpha1.AwsSesIdentityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsSesIdentityPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAwsSesIdentityPolicies) UpdateStatus(awsSesIdentityPolicy *v1alpha1.AwsSesIdentityPolicy) (*v1alpha1.AwsSesIdentityPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(awssesidentitypoliciesResource, "status", awsSesIdentityPolicy), &v1alpha1.AwsSesIdentityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsSesIdentityPolicy), err
}

// Delete takes name of the awsSesIdentityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeAwsSesIdentityPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(awssesidentitypoliciesResource, name), &v1alpha1.AwsSesIdentityPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsSesIdentityPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(awssesidentitypoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsSesIdentityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched awsSesIdentityPolicy.
func (c *FakeAwsSesIdentityPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AwsSesIdentityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(awssesidentitypoliciesResource, name, pt, data, subresources...), &v1alpha1.AwsSesIdentityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsSesIdentityPolicy), err
}
